import type { StateData } from './types';

/**
 * All 28 states and 8 union territories of India with district coverage and
 * state-specific design context. Intros are written per state so hub pages
 * are not templated boilerplate.
 */
export const STATES: StateData[] = [
  // ───────────────────────────── EAST ─────────────────────────────
  {
    slug: 'west-bengal',
    name: 'West Bengal',
    kind: 'state',
    capital: 'Kolkata',
    region: 'East',
    languages: ['Bengali'],
    districts: [
      'Alipurduar',
      'Bankura',
      'Birbhum',
      'Cooch Behar',
      'Dakshin Dinajpur',
      'Darjeeling',
      'Hooghly',
      'Howrah',
      'Jalpaiguri',
      'Jhargram',
      'Kalimpong',
      'Kolkata',
      'Malda',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'Paschim Bardhaman',
      'Paschim Medinipur',
      'Purba Bardhaman',
      'Purba Medinipur',
      'Purulia',
      'South 24 Parganas',
      'Uttar Dinajpur',
    ],
    intro:
      'West Bengal is home ground for Silver Storey — our head office sits in Tangra, Kolkata, and a large share of our 50,000+ sq ft portfolio is spread across the city, Howrah, New Town and the Rajarhat corridor. The state mixes century-old heritage homes with dense high-rise townships, so we design as comfortably around a north-Kolkata courtyard as we do around a 3BHK on EM Bypass.',
    designNotes: [
      'Monsoon humidity is relentless from June to September; we specify BWP (boiling water proof) plywood, marine-grade adhesives and HDHMR for wet zones by default.',
      'Older Kolkata homes have 11–13 ft ceilings and thick brick walls — ideal for tall wardrobes, mezzanine storage and false-ceiling cove lighting without feeling cramped.',
      'Local craftsmanship is strong: solid teak, sheesham and cane work from Bengal artisans lets us build bespoke furniture at competitive cost.',
      'Rajarhat, New Town and Joka apartments often come with compact kitchens; we plan L-shaped and parallel modular kitchens that maximise counter length in 8–10 ft spans.',
    ],
  },
  {
    slug: 'odisha',
    name: 'Odisha',
    kind: 'state',
    capital: 'Bhubaneswar',
    region: 'East',
    languages: ['Odia'],
    districts: [
      'Angul',
      'Balangir',
      'Balasore',
      'Bargarh',
      'Bhadrak',
      'Boudh',
      'Cuttack',
      'Deogarh',
      'Dhenkanal',
      'Gajapati',
      'Ganjam',
      'Jagatsinghpur',
      'Jajpur',
      'Jharsuguda',
      'Kalahandi',
      'Kandhamal',
      'Kendrapara',
      'Kendujhar',
      'Khordha',
      'Koraput',
      'Malkangiri',
      'Mayurbhanj',
      'Nabarangpur',
      'Nayagarh',
      'Nuapada',
      'Puri',
      'Rayagada',
      'Sambalpur',
      'Subarnapur',
      'Sundargarh',
    ],
    intro:
      'Odisha is one of the fastest-growing interior markets in eastern India, driven by the Bhubaneswar–Cuttack–Puri triangle and IT and industrial hubs in Rourkela and Sambalpur. Buyers here favour warm, temple-inspired detailing balanced with clean modern planning, and the state’s new gated communities are a natural fit for our turnkey model.',
    designNotes: [
      'Coastal districts like Puri and Balasore face salt-laden air and cyclonic weather; we use SS-304 hardware, powder-coated aluminium and anti-corrosive treatments on all exposed metal.',
      'Pattachitra, Sambalpuri ikat and stone carving traditions give us authentic accent options for feature walls and upholstery.',
      'Bhubaneswar’s planned layouts (Chandrasekharpur, Patia, Nayapalli) have generous plot sizes, allowing spacious open-plan living and dining.',
    ],
  },
  {
    slug: 'bihar',
    name: 'Bihar',
    kind: 'state',
    capital: 'Patna',
    region: 'East',
    districts: [
      'Araria',
      'Arwal',
      'Aurangabad',
      'Banka',
      'Begusarai',
      'Bhagalpur',
      'Bhojpur',
      'Buxar',
      'Darbhanga',
      'East Champaran',
      'Gaya',
      'Gopalganj',
      'Jamui',
      'Jehanabad',
      'Kaimur',
      'Katihar',
      'Khagaria',
      'Kishanganj',
      'Lakhisarai',
      'Madhepura',
      'Madhubani',
      'Munger',
      'Muzaffarpur',
      'Nalanda',
      'Nawada',
      'Patna',
      'Purnia',
      'Rohtas',
      'Saharsa',
      'Samastipur',
      'Saran',
      'Sheikhpura',
      'Sheohar',
      'Sitamarhi',
      'Siwan',
      'Supaul',
      'Vaishali',
      'West Champaran',
    ],
    intro:
      'Bihar’s interior market is anchored by Patna, where new apartment complexes along Bailey Road, Kankarbagh and Danapur are replacing older independent houses. Families here typically want multi-generational layouts — separate pooja rooms, large dining spaces and durable finishes that stand up to heavy daily use.',
    designNotes: [
      'Summers regularly cross 42°C; we favour light-reflective laminates, cross-ventilated layouts and heat-resistant PU finishes on sun-facing joinery.',
      'Madhubani (Mithila) art is a distinctive, region-specific accent we integrate into feature walls and headboards.',
      'Many plots are large and self-built; we frequently plan interiors for duplex and triplex independent homes, not just apartments.',
    ],
  },
  {
    slug: 'jharkhand',
    name: 'Jharkhand',
    kind: 'state',
    capital: 'Ranchi',
    region: 'East',
    districts: [
      'Bokaro',
      'Chatra',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'East Singhbhum',
      'Garhwa',
      'Giridih',
      'Godda',
      'Gumla',
      'Hazaribagh',
      'Jamtara',
      'Khunti',
      'Koderma',
      'Latehar',
      'Lohardaga',
      'Pakur',
      'Palamu',
      'Ramgarh',
      'Ranchi',
      'Sahibganj',
      'Seraikela-Kharsawan',
      'Simdega',
      'West Singhbhum',
    ],
    intro:
      'Jharkhand’s design demand is concentrated in Ranchi, Jamshedpur, Dhanbad and Bokaro — planned industrial cities with a professional, salaried population that values well-engineered, low-maintenance homes. Being a short drive from Kolkata, these cities are among the most frequently visited by our execution team.',
    designNotes: [
      'Jamshedpur’s Tata-planned neighbourhoods have consistent floor plans, letting us reuse proven layouts while personalising finishes.',
      'Ranchi’s plateau climate is milder than the plains, so natural wood and veneers age well here with standard sealing.',
      'Sohrai and Khovar tribal wall art are unique local motifs for accent walls and textiles.',
    ],
  },

  // ───────────────────────────── NORTH ─────────────────────────────
  {
    slug: 'delhi',
    name: 'Delhi',
    kind: 'ut',
    capital: 'New Delhi',
    region: 'North',
    districts: [
      'Central Delhi',
      'East Delhi',
      'New Delhi',
      'North Delhi',
      'North East Delhi',
      'North West Delhi',
      'Shahdara',
      'South Delhi',
      'South East Delhi',
      'South West Delhi',
      'West Delhi',
    ],
    intro:
      'Delhi is India’s most design-literate residential market — from builder floors in Greater Kailash and Vasant Vihar to luxury apartments in Dwarka and the DDA flats being reimagined across the city. Clients expect strong material knowledge, precise detailing and confident use of colour, and we bring exactly that to every project in the capital.',
    designNotes: [
      'Builder floors with 4–5 sides open are common in South Delhi; we plan layouts around natural light and cross-ventilation rather than fighting them.',
      'Extreme summers and dusty winters call for sealed shutters, soft-close hardware and finishes that don’t show dust — matte laminates and textured veneers perform best.',
      'Lutyens-era bungalows and Civil Lines homes benefit from restoration-sensitive design: lime plaster, terrazzo repair and period-appropriate millwork.',
      'Proximity to Kirti Nagar furniture market and the Gurugram/Noida vendor ecosystem shortens sourcing lead times.',
    ],
  },
  {
    slug: 'haryana',
    name: 'Haryana',
    kind: 'state',
    capital: 'Chandigarh',
    region: 'North',
    districts: [
      'Ambala',
      'Bhiwani',
      'Charkhi Dadri',
      'Faridabad',
      'Fatehabad',
      'Gurugram',
      'Hisar',
      'Jhajjar',
      'Jind',
      'Kaithal',
      'Karnal',
      'Kurukshetra',
      'Mahendragarh',
      'Nuh',
      'Palwal',
      'Panchkula',
      'Panipat',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
      'Yamunanagar',
    ],
    intro:
      'Haryana’s interior demand is dominated by Gurugram and Faridabad — the two NCR powerhouses where premium condominiums along Golf Course Road, Sohna Road and Greater Faridabad set the benchmark for luxury living in North India. The state also has a fast-emerging market in Panchkula, Karnal and Panipat.',
    designNotes: [
      'Gurugram high-rises often hand over “bare-shell” or “warm-shell” apartments, so we deliver full-scope interiors including flooring, electricals and false ceilings.',
      'Large balconies and double-height living rooms are common in DLF, M3M and Emaar projects — we design for scale with statement lighting and full-height panelling.',
      'The Panipat textile belt gives us direct access to handloom rugs, dhurries and upholstery fabric at source prices.',
    ],
  },
  {
    slug: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    kind: 'state',
    capital: 'Lucknow',
    region: 'North',
    districts: [
      'Agra',
      'Aligarh',
      'Ambedkar Nagar',
      'Amethi',
      'Amroha',
      'Auraiya',
      'Ayodhya',
      'Azamgarh',
      'Baghpat',
      'Bahraich',
      'Ballia',
      'Balrampur',
      'Banda',
      'Barabanki',
      'Bareilly',
      'Basti',
      'Bhadohi',
      'Bijnor',
      'Budaun',
      'Bulandshahr',
      'Chandauli',
      'Chitrakoot',
      'Deoria',
      'Etah',
      'Etawah',
      'Farrukhabad',
      'Fatehpur',
      'Firozabad',
      'Gautam Buddha Nagar',
      'Ghaziabad',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hamirpur',
      'Hapur',
      'Hardoi',
      'Hathras',
      'Jalaun',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur Dehat',
      'Kanpur Nagar',
      'Kasganj',
      'Kaushambi',
      'Kushinagar',
      'Lakhimpur Kheri',
      'Lalitpur',
      'Lucknow',
      'Maharajganj',
      'Mahoba',
      'Mainpuri',
      'Mathura',
      'Mau',
      'Meerut',
      'Mirzapur',
      'Moradabad',
      'Muzaffarnagar',
      'Pilibhit',
      'Pratapgarh',
      'Prayagraj',
      'Raebareli',
      'Rampur',
      'Saharanpur',
      'Sambhal',
      'Sant Kabir Nagar',
      'Shahjahanpur',
      'Shamli',
      'Shravasti',
      'Siddharthnagar',
      'Sitapur',
      'Sonbhadra',
      'Sultanpur',
      'Unnao',
      'Varanasi',
    ],
    intro:
      'Uttar Pradesh spans two very different interior markets: the NCR cities of Noida, Greater Noida and Ghaziabad, where high-rise apartment culture mirrors Delhi and Gurugram, and the heartland cities of Lucknow, Kanpur, Varanasi, Agra and Prayagraj, where large independent homes and a taste for Awadhi and Mughal-influenced detailing shape the brief.',
    designNotes: [
      'Lucknow clients often ask for jaali screens, chikankari-inspired textures and arched niches — we translate these into contemporary joinery rather than pastiche.',
      'Noida Expressway and Greater Noida West towers have standard 2BHK/3BHK plates; we have optimised modular kitchen and wardrobe kits for these exact dimensions.',
      'Saharanpur is India’s wood-carving capital and Moradabad its brassware hub — both are sourcing advantages for bespoke furniture and hardware.',
      'Hot, dry summers and foggy winters mean we seal all wood and use anti-fungal primers behind wardrobes on external walls.',
    ],
  },
  {
    slug: 'punjab',
    name: 'Punjab',
    kind: 'state',
    capital: 'Chandigarh',
    region: 'North',
    languages: ['Punjabi'],
    districts: [
      'Amritsar',
      'Barnala',
      'Bathinda',
      'Faridkot',
      'Fatehgarh Sahib',
      'Fazilka',
      'Ferozepur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Malerkotla',
      'Mansa',
      'Moga',
      'Muktsar',
      'Pathankot',
      'Patiala',
      'Rupnagar',
      'Sahibzada Ajit Singh Nagar (Mohali)',
      'Sangrur',
      'Shaheed Bhagat Singh Nagar',
      'Tarn Taran',
    ],
    intro:
      'Punjab’s homes are famously generous — kothis on 500 sq yd plots in Ludhiana, Jalandhar and Amritsar, and premium apartments in Mohali and Zirakpur close to Chandigarh. Clients favour bold, celebratory interiors: large formal drawing rooms, statement ceilings and kitchens built for serious cooking.',
    designNotes: [
      'Independent kothis let us design full-height entrance foyers, sweeping staircases and formal plus family living zones.',
      'NRI-owned homes are common; we run the entire project remotely with weekly video walkthroughs and 3D approvals.',
      'Kartarpur and Jalandhar have a deep furniture-making tradition — solid sheesham and teak pieces are made to order locally.',
    ],
  },
  {
    slug: 'chandigarh',
    name: 'Chandigarh',
    kind: 'ut',
    capital: 'Chandigarh',
    region: 'North',
    districts: ['Chandigarh'],
    intro:
      'Chandigarh is India’s most famous planned city, and its Le Corbusier-era grid, sector housing and strict façade controls shape what interiors can be. We work within the modernist envelope — clean lines, honest materials, generous daylight — while adding the warmth and storage that today’s families need.',
    designNotes: [
      'Sector homes have fixed frontages and courtyards; interiors are where personality is expressed, so we invest in joinery and lighting design.',
      'The Corbusier legacy makes exposed brick, terrazzo and concrete finishes locally appropriate and much loved.',
      'Adjacent Panchkula and Mohali share the same design sensibility and vendor base.',
    ],
  },
  {
    slug: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    kind: 'state',
    capital: 'Shimla',
    region: 'North',
    districts: [
      'Bilaspur',
      'Chamba',
      'Hamirpur',
      'Kangra',
      'Kinnaur',
      'Kullu',
      'Lahaul and Spiti',
      'Mandi',
      'Shimla',
      'Sirmaur',
      'Solan',
      'Una',
    ],
    intro:
      'Himachal Pradesh brings a distinct brief: holiday homes, boutique homestays and permanent hill residences in Shimla, Dharamshala, Kasauli, Manali and the Solan–Parwanoo industrial belt. Design here is about warmth, insulation and framing mountain views — while respecting the region’s timber-and-stone building heritage.',
    designNotes: [
      'Cold winters mean we prioritise insulation, double-glazed windows, wooden flooring with underlay and radiant heating provisions.',
      'Deodar and pine are local; we combine them with engineered wood to avoid seasonal movement in joinery.',
      'Kath-kuni (interlocking timber and stone) is a genuine regional vernacular we reference in feature walls and ceilings.',
    ],
  },
  {
    slug: 'uttarakhand',
    name: 'Uttarakhand',
    kind: 'state',
    capital: 'Dehradun',
    region: 'North',
    districts: [
      'Almora',
      'Bageshwar',
      'Chamoli',
      'Champawat',
      'Dehradun',
      'Haridwar',
      'Nainital',
      'Pauri Garhwal',
      'Pithoragarh',
      'Rudraprayag',
      'Tehri Garhwal',
      'Udham Singh Nagar',
      'Uttarkashi',
    ],
    intro:
      'Uttarakhand’s interior demand centres on Dehradun — a fast-growing education and retirement city — along with Haridwar, Rishikesh, Roorkee, Haldwani and hill homes in Mussoorie and Nainital. Buyers want calm, nature-led interiors that use wood and stone honestly and cope well with the sub-Himalayan climate.',
    designNotes: [
      'Dehradun valley homes get heavy monsoon rain and chilly winters; we treat all timber and prefer WPC/HDHMR in bathrooms and utility areas.',
      'Wellness and yoga-inspired spaces are a frequent ask in Rishikesh and Haridwar — meditation nooks, natural lime finishes and low-VOC paints.',
      'Hill sites in Mussoorie and Nainital have narrow access; we prefabricate modular units in our workshop and assemble on site.',
    ],
  },
  {
    slug: 'jammu-and-kashmir',
    name: 'Jammu and Kashmir',
    kind: 'ut',
    capital: 'Srinagar / Jammu',
    region: 'North',
    districts: [
      'Anantnag',
      'Bandipora',
      'Baramulla',
      'Budgam',
      'Doda',
      'Ganderbal',
      'Jammu',
      'Kathua',
      'Kishtwar',
      'Kulgam',
      'Kupwara',
      'Poonch',
      'Pulwama',
      'Rajouri',
      'Ramban',
      'Reasi',
      'Samba',
      'Shopian',
      'Srinagar',
      'Udhampur',
    ],
    intro:
      'Jammu and Kashmir has one of India’s richest craft traditions — khatamband ceilings, pinjrakari lattice, walnut wood carving and hand-knotted carpets. We design interiors in Jammu and Srinagar that honour these crafts while delivering the insulation, heating provisions and modern storage that valley winters demand.',
    designNotes: [
      'Srinagar winters drop below freezing; we specify insulated walls, double glazing and provisions for bukhari or radiant heating in living zones.',
      'Kashmiri walnut and papier-mâché work are genuine local luxuries that we source directly from artisan families.',
      'Jammu’s warmer plains climate allows conventional material palettes similar to Punjab and Haryana.',
    ],
  },
  {
    slug: 'ladakh',
    name: 'Ladakh',
    kind: 'ut',
    capital: 'Leh',
    region: 'North',
    districts: ['Leh', 'Kargil'],
    intro:
      'Ladakh’s high-altitude desert climate demands a completely different approach to interiors: passive solar orientation, thick insulated envelopes, and materials that tolerate extreme dryness and UV. We work on guesthouses, hotels and homes in Leh with a focus on thermal comfort and honest, earthy palettes.',
    designNotes: [
      'Extreme cold and dryness cause wood to crack; we use engineered boards, kiln-dried timber and humidity-stable finishes.',
      'Traditional Ladakhi timber ceilings, rammed-earth walls and low seating inform our layouts.',
      'Logistics are seasonal — we prefabricate and ship modular units before the passes close.',
    ],
  },

  // ───────────────────────────── WEST ─────────────────────────────
  {
    slug: 'maharashtra',
    name: 'Maharashtra',
    kind: 'state',
    capital: 'Mumbai',
    region: 'West',
    languages: ['Marathi'],
    districts: [
      'Ahilyanagar (Ahmednagar)',
      'Akola',
      'Amravati',
      'Beed',
      'Bhandara',
      'Buldhana',
      'Chandrapur',
      'Chhatrapati Sambhajinagar (Aurangabad)',
      'Dharashiv (Osmanabad)',
      'Dhule',
      'Gadchiroli',
      'Gondia',
      'Hingoli',
      'Jalgaon',
      'Jalna',
      'Kolhapur',
      'Latur',
      'Mumbai City',
      'Mumbai Suburban',
      'Nagpur',
      'Nanded',
      'Nandurbar',
      'Nashik',
      'Palghar',
      'Parbhani',
      'Pune',
      'Raigad',
      'Ratnagiri',
      'Sangli',
      'Satara',
      'Sindhudurg',
      'Solapur',
      'Thane',
      'Wardha',
      'Washim',
      'Yavatmal',
    ],
    intro:
      'Maharashtra is India’s largest interior design market, led by Mumbai’s space-starved luxury apartments, Pune’s IT-driven townships and Nagpur’s expanding residential belt. Every square foot matters in Mumbai, so our designs lean on multifunctional furniture, ceiling-height storage and layouts that make 650 sq ft feel like 900.',
    designNotes: [
      'Mumbai and Thane are humid and salty year-round; BWP ply, marine adhesives and SS-304 hardware are non-negotiable for coastal wards.',
      'Pune’s Hinjewadi, Kharadi, Wakad and Baner corridors have thousands of similar 2BHK/3BHK plans — we have refined kits for these layouts.',
      'Redevelopment projects in Mumbai often hand over compact, oddly shaped flats; we use custom carpentry to reclaim every corner.',
      'Warli art, Paithani weaves and Kolhapuri leather are regional accents we use with restraint for authentic local character.',
    ],
  },
  {
    slug: 'gujarat',
    name: 'Gujarat',
    kind: 'state',
    capital: 'Gandhinagar',
    region: 'West',
    languages: ['Gujarati'],
    districts: [
      'Ahmedabad',
      'Amreli',
      'Anand',
      'Aravalli',
      'Banaskantha',
      'Bharuch',
      'Bhavnagar',
      'Botad',
      'Chhota Udaipur',
      'Dahod',
      'Dang',
      'Devbhoomi Dwarka',
      'Gandhinagar',
      'Gir Somnath',
      'Jamnagar',
      'Junagadh',
      'Kheda',
      'Kutch',
      'Mahisagar',
      'Mehsana',
      'Morbi',
      'Narmada',
      'Navsari',
      'Panchmahal',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Sabarkantha',
      'Surat',
      'Surendranagar',
      'Tapi',
      'Vadodara',
      'Valsad',
    ],
    intro:
      'Gujarat combines a deep vernacular design heritage — pol houses, Kutch mirror-work, Morbi ceramics — with some of India’s most modern residential developments in Ahmedabad’s SG Highway belt, GIFT City and Surat’s Vesu–Pal corridor. Homes here are family-centric, with large gathering spaces, dedicated pooja rooms and kitchens designed for elaborate vegetarian cooking.',
    designNotes: [
      'Morbi is the world’s largest tile cluster; we source vitrified and large-format tiles at factory prices for Gujarat projects.',
      'Dry summers above 44°C in Ahmedabad make heat-reflective finishes, deep verandas and cross-ventilation part of the layout logic.',
      'Traditional hinchko (swing) seating, jharokha-style niches and brass detailing are popular and authentically Gujarati.',
      'Surat’s diamond and textile wealth supports a strong luxury bungalow market with double-height living rooms and home theatres.',
    ],
  },
  {
    slug: 'rajasthan',
    name: 'Rajasthan',
    kind: 'state',
    capital: 'Jaipur',
    region: 'West',
    districts: [
      'Ajmer',
      'Alwar',
      'Balotra',
      'Banswara',
      'Baran',
      'Barmer',
      'Beawar',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Bundi',
      'Chittorgarh',
      'Churu',
      'Dausa',
      'Deeg',
      'Dholpur',
      'Didwana-Kuchaman',
      'Dungarpur',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalore',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Karauli',
      'Khairthal-Tijara',
      'Kota',
      'Kotputli-Behror',
      'Nagaur',
      'Pali',
      'Phalodi',
      'Pratapgarh',
      'Rajsamand',
      'Salumbar',
      'Sawai Madhopur',
      'Sikar',
      'Sirohi',
      'Sri Ganganagar',
      'Tonk',
      'Udaipur',
    ],
    intro:
      'Rajasthan is where Indian interiors draw their most iconic vocabulary — jharokhas, jaalis, lime-plastered araish walls, block-printed textiles and hand-carved stone. In Jaipur, Jodhpur, Udaipur and Kota we design homes that borrow from this heritage with a light hand, pairing it with modern modular systems built to survive desert heat.',
    designNotes: [
      'Extreme dry heat and dust mean sealed cabinetry, heat-stable PU/acrylic finishes and stone flooring that stays cool underfoot.',
      'Kishangarh marble and Jodhpur sandstone are local — feature walls, countertops and flooring can be sourced at origin prices.',
      'Jaipur’s Sanganer and Bagru block-print clusters supply bespoke upholstery and drapery.',
      'Havelis and heritage conversions in Jodhpur and Udaipur need conservation-aware design: lime mortar, traditional araish and period joinery.',
    ],
  },
  {
    slug: 'goa',
    name: 'Goa',
    kind: 'state',
    capital: 'Panaji',
    region: 'West',
    languages: ['Konkani'],
    districts: ['North Goa', 'South Goa'],
    intro:
      'Goa is India’s second-home and boutique-hospitality capital, and its Indo-Portuguese houses — with their azulejo tiles, oyster-shell windows and deep balcãos — set a design language unlike anywhere else. We work on villas in Assagao, Siolim and Anjuna, apartments in Panaji and Margao, and hospitality interiors along both coasts.',
    designNotes: [
      'Tropical coastal humidity is severe; we rely on marine ply, teak, terrazzo and lime plaster that breathe rather than trap moisture.',
      'Indo-Portuguese elements — patterned cement tiles, laterite stone, high ceilings and louvred shutters — are authentic to the region.',
      'Rental and hospitality villas need robust, easy-clean finishes and layouts that photograph well.',
    ],
  },
  {
    slug: 'dadra-and-nagar-haveli-and-daman-and-diu',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    kind: 'ut',
    capital: 'Daman',
    region: 'West',
    districts: ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
    intro:
      'Silvassa, Daman and Diu form a compact coastal union territory with a strong industrial base and a growing set of holiday homes. Interiors here need to handle salt air and humidity while delivering the relaxed, resort-like feel that second-home owners want.',
    designNotes: [
      'Coastal exposure means marine-grade boards and stainless hardware throughout.',
      'Portuguese-era architecture in Daman and Diu offers a heritage palette of lime, laterite and patterned tiles.',
      'Silvassa’s industrial townships need efficient, durable interiors for company-provided housing.',
    ],
  },

  // ───────────────────────────── SOUTH ─────────────────────────────
  {
    slug: 'karnataka',
    name: 'Karnataka',
    kind: 'state',
    capital: 'Bengaluru',
    region: 'South',
    languages: ['Kannada'],
    districts: [
      'Bagalkot',
      'Ballari',
      'Belagavi',
      'Bengaluru Rural',
      'Bengaluru Urban',
      'Bidar',
      'Chamarajanagar',
      'Chikkaballapur',
      'Chikkamagaluru',
      'Chitradurga',
      'Dakshina Kannada',
      'Davanagere',
      'Dharwad',
      'Gadag',
      'Hassan',
      'Haveri',
      'Kalaburagi',
      'Kodagu',
      'Kolar',
      'Koppal',
      'Mandya',
      'Mysuru',
      'Raichur',
      'Ramanagara',
      'Shivamogga',
      'Tumakuru',
      'Udupi',
      'Uttara Kannada',
      'Vijayanagara',
      'Vijayapura',
      'Yadgir',
    ],
    intro:
      'Karnataka’s interior market is defined by Bengaluru — the country’s tech capital, where a young, well-travelled population in Whitefield, Sarjapur, Hebbal and Electronic City wants Scandinavian-clean, tech-integrated homes. Beyond the capital, Mysuru’s heritage homes and Mangaluru’s coastal residences bring very different, equally rewarding briefs.',
    designNotes: [
      'Bengaluru’s moderate climate is forgiving on materials, so natural veneers, solid wood and open shelving age beautifully.',
      'Gated villa communities off Sarjapur Road and Kanakapura Road have large plot sizes and double-height spaces that suit statement staircases and libraries.',
      'Mangaluru and Udupi face Arabian Sea humidity — marine ply and terracotta (Mangalore tiles) are both practical and local.',
      'Mysuru rosewood inlay and Channapatna lacquerware are authentic regional accents.',
    ],
  },
  {
    slug: 'tamil-nadu',
    name: 'Tamil Nadu',
    kind: 'state',
    capital: 'Chennai',
    region: 'South',
    languages: ['Tamil'],
    districts: [
      'Ariyalur',
      'Chengalpattu',
      'Chennai',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kallakurichi',
      'Kanchipuram',
      'Kanyakumari',
      'Karur',
      'Krishnagiri',
      'Madurai',
      'Mayiladuthurai',
      'Nagapattinam',
      'Namakkal',
      'Nilgiris',
      'Perambalur',
      'Pudukkottai',
      'Ramanathapuram',
      'Ranipet',
      'Salem',
      'Sivaganga',
      'Tenkasi',
      'Thanjavur',
      'Theni',
      'Thoothukudi',
      'Tiruchirappalli',
      'Tirunelveli',
      'Tirupattur',
      'Tiruppur',
      'Tiruvallur',
      'Tiruvannamalai',
      'Tiruvarur',
      'Vellore',
      'Viluppuram',
      'Virudhunagar',
    ],
    intro:
      'Tamil Nadu pairs a strong traditional aesthetic — Chettinad courtyards, Athangudi tiles, Burma teak — with the modern apartment markets of Chennai’s OMR, ECR and Porur corridors, and the industrial wealth of Coimbatore and Tiruppur. Vastu compliance, dedicated pooja spaces and heat-conscious planning are almost always part of the brief.',
    designNotes: [
      'Chennai’s coastal heat and humidity mean we favour BWP boards, ventilated wardrobes and light, breathable colour palettes.',
      'Chettinad and Karaikudi supply antique doors, pillars and Athangudi handmade tiles for authentic feature elements.',
      'Coimbatore has a mature manufacturing base — modular hardware, motors and custom metalwork are produced locally.',
      'Independent houses with courtyards remain common in Madurai, Trichy and Salem; we design around the central mutram.',
    ],
  },
  {
    slug: 'telangana',
    name: 'Telangana',
    kind: 'state',
    capital: 'Hyderabad',
    region: 'South',
    languages: ['Telugu'],
    districts: [
      'Adilabad',
      'Bhadradri Kothagudem',
      'Hanumakonda',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Jayashankar Bhupalpally',
      'Jogulamba Gadwal',
      'Kamareddy',
      'Karimnagar',
      'Khammam',
      'Komaram Bheem Asifabad',
      'Mahabubabad',
      'Mahabubnagar',
      'Mancherial',
      'Medak',
      'Medchal–Malkajgiri',
      'Mulugu',
      'Nagarkurnool',
      'Nalgonda',
      'Narayanpet',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Rajanna Sircilla',
      'Rangareddy',
      'Sangareddy',
      'Siddipet',
      'Suryapet',
      'Vikarabad',
      'Wanaparthy',
      'Warangal',
      'Yadadri Bhuvanagiri',
    ],
    intro:
      'Telangana’s interior boom is Hyderabad’s — the western corridor of Gachibowli, Kokapet, Narsingi and Tellapur has some of India’s largest apartment towers and villa communities, and buyers here have high expectations of finish quality and smart-home integration. Warangal, Karimnagar and Nizamabad are growing secondary markets.',
    designNotes: [
      'Hyderabad’s new towers often have 3,000–5,000 sq ft “sky villas” — we plan multi-zone living, home theatres and staff areas as standard.',
      'Composite climate with hot summers: we use light palettes, UV-stable finishes and shaded balconies as extensions of living space.',
      'Nirmal paintings, Pochampally ikat and Bidriware are distinctive regional accents.',
      'Smart-home automation (lighting, curtains, AC) is requested in most premium Hyderabad projects and is part of our standard scope.',
    ],
  },
  {
    slug: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    kind: 'state',
    capital: 'Amaravati',
    region: 'South',
    languages: ['Telugu'],
    districts: [
      'Alluri Sitharama Raju',
      'Anakapalli',
      'Anantapur',
      'Annamayya',
      'Bapatla',
      'Chittoor',
      'Dr. B.R. Ambedkar Konaseema',
      'East Godavari',
      'Eluru',
      'Guntur',
      'Kakinada',
      'Krishna',
      'Kurnool',
      'Nandyal',
      'NTR',
      'Palnadu',
      'Parvathipuram Manyam',
      'Prakasam',
      'Sri Potti Sriramulu Nellore',
      'Sri Sathya Sai',
      'Srikakulam',
      'Tirupati',
      'Visakhapatnam',
      'Vizianagaram',
      'West Godavari',
      'YSR Kadapa',
    ],
    intro:
      'Andhra Pradesh’s interior demand runs along the coast — Visakhapatnam’s sea-facing apartments, the Vijayawada–Guntur–Amaravati capital region and Tirupati’s pilgrimage-driven hospitality market. Homes here are spacious, family-oriented and increasingly influenced by Hyderabad’s premium finishing standards.',
    designNotes: [
      'Vizag and Kakinada get Bay of Bengal humidity and cyclones; corrosion-resistant hardware and marine boards are mandatory.',
      'Kondapalli toys, Kalamkari fabric and Etikoppaka lacquerware are regional crafts we fold into accents and upholstery.',
      'Large independent houses in Guntur, Nellore and Rajahmundry commonly include a formal hall, family hall and separate pooja room.',
    ],
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    kind: 'state',
    capital: 'Thiruvananthapuram',
    region: 'South',
    languages: ['Malayalam'],
    districts: [
      'Alappuzha',
      'Ernakulam',
      'Idukki',
      'Kannur',
      'Kasaragod',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Malappuram',
      'Palakkad',
      'Pathanamthitta',
      'Thiruvananthapuram',
      'Thrissur',
      'Wayanad',
    ],
    intro:
      'Kerala has one of India’s most distinctive residential traditions — the nalukettu courtyard house, sloping tiled roofs, and rosewood and teak joinery — and one of its highest rates of NRI-funded home building. In Kochi, Thiruvananthapuram, Kozhikode and Thrissur, we design tropical-modern interiors that stay cool, dry and elegant through the long monsoon.',
    designNotes: [
      'Annual rainfall above 3,000 mm means moisture control is the first design decision: BWP ply, ventilated cabinetry and lime or breathable paints.',
      'Traditional elements — charupadi seating, wooden ceilings, Athangudi and terracotta floors — pair naturally with modern kitchens.',
      'NRI clients typically approve everything remotely; our 3D visualisation and weekly reporting workflow was built for exactly this.',
      'Vastu (thachu shastra) compliance is expected and integrated into layouts from day one.',
    ],
  },
  {
    slug: 'puducherry',
    name: 'Puducherry',
    kind: 'ut',
    capital: 'Puducherry',
    region: 'South',
    languages: ['Tamil'],
    districts: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
    intro:
      'Puducherry’s White Town and Tamil Quarter preserve a French-colonial and Franco-Tamil architectural language — mustard walls, tall louvred windows, courtyards and lime plaster — that inspires a unique, breezy interior style. We work on heritage homes, cafés, guesthouses and new apartments across Pondicherry and Karaikal.',
    designNotes: [
      'Coastal humidity calls for breathable lime finishes, terracotta and marine-grade joinery.',
      'French-colonial proportions favour tall furniture, ceiling fans as design elements and soft ochre/blue palettes.',
      'Auroville’s earth-architecture movement supplies rammed-earth, ferrocement and sustainable material expertise locally.',
    ],
  },
  {
    slug: 'lakshadweep',
    name: 'Lakshadweep',
    kind: 'ut',
    capital: 'Kavaratti',
    region: 'South',
    districts: ['Lakshadweep'],
    intro:
      'Lakshadweep’s island homes and resorts require interiors that survive constant salt spray, high humidity and logistical constraints. We plan prefabricated, marine-grade fit-outs shipped from the mainland and assembled on site.',
    designNotes: [
      'Only marine ply, solid teak, SS-316 hardware and fibre-cement boards are specified.',
      'Coral-sensitive construction rules favour lightweight, dry-assembly interiors.',
      'All units are prefabricated and containerised for sea transport.',
    ],
  },
  {
    slug: 'andaman-and-nicobar-islands',
    name: 'Andaman and Nicobar Islands',
    kind: 'ut',
    capital: 'Port Blair',
    region: 'South',
    districts: ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
    intro:
      'Port Blair, Havelock (Swaraj Dweep) and Neil (Shaheed Dweep) have a growing resort and second-home market that demands tropical, resilient interiors. We design for constant humidity, seismic considerations and sea-freight logistics, using Andaman padauk and marine-grade systems.',
    designNotes: [
      'Padauk and gurjan are local hardwoods; we pair them with marine ply and SS-316 fittings.',
      'Open, cross-ventilated layouts with ceiling fans reduce reliance on air conditioning.',
      'All modular units are prefabricated on the mainland and shipped ready to assemble.',
    ],
  },

  // ───────────────────────────── CENTRAL ─────────────────────────────
  {
    slug: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    kind: 'state',
    capital: 'Bhopal',
    region: 'Central',
    districts: [
      'Agar Malwa',
      'Alirajpur',
      'Anuppur',
      'Ashoknagar',
      'Balaghat',
      'Barwani',
      'Betul',
      'Bhind',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Dindori',
      'Guna',
      'Gwalior',
      'Harda',
      'Indore',
      'Jabalpur',
      'Jhabua',
      'Katni',
      'Khandwa',
      'Khargone',
      'Maihar',
      'Mandla',
      'Mandsaur',
      'Mauganj',
      'Morena',
      'Narmadapuram',
      'Narsinghpur',
      'Neemuch',
      'Niwari',
      'Pandhurna',
      'Panna',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Sidhi',
      'Singrauli',
      'Tikamgarh',
      'Ujjain',
      'Umaria',
      'Vidisha',
    ],
    intro:
      'Madhya Pradesh’s interior market is led by Indore — India’s cleanest city and a booming commercial hub with premium townships along the Super Corridor and AB Road — followed by Bhopal’s lake-side residences, Jabalpur and Gwalior. Homes here are large, and clients appreciate warm, well-crafted interiors with a strong sense of family gathering.',
    designNotes: [
      'Central India’s hot, dry summers and mild winters allow a broad material palette; we still seal wood against seasonal humidity swings.',
      'Bhopal’s Gond art and Maheshwari and Chanderi weaves are regional textures we bring into soft furnishings and accent walls.',
      'Indore’s Vijay Nagar, Scheme 54 and Bicholi Mardana developments have a strong villa-plot culture ideal for full turnkey design.',
    ],
  },
  {
    slug: 'chhattisgarh',
    name: 'Chhattisgarh',
    kind: 'state',
    capital: 'Raipur',
    region: 'Central',
    districts: [
      'Balod',
      'Baloda Bazar',
      'Balrampur',
      'Bastar',
      'Bemetara',
      'Bijapur',
      'Bilaspur',
      'Dantewada',
      'Dhamtari',
      'Durg',
      'Gariaband',
      'Gaurela-Pendra-Marwahi',
      'Janjgir-Champa',
      'Jashpur',
      'Kabirdham',
      'Kanker',
      'Khairagarh-Chhuikhadan-Gandai',
      'Kondagaon',
      'Korba',
      'Koriya',
      'Mahasamund',
      'Manendragarh-Chirmiri-Bharatpur',
      'Mohla-Manpur-Ambagarh Chowki',
      'Mungeli',
      'Narayanpur',
      'Raigarh',
      'Raipur',
      'Rajnandgaon',
      'Sakti',
      'Sarangarh-Bilaigarh',
      'Sukma',
      'Surajpur',
      'Surguja',
    ],
    intro:
      'Chhattisgarh’s demand is centred on Raipur and the planned capital Nava Raipur (Atal Nagar), plus the industrial cities of Bhilai, Durg, Bilaspur and Korba. A rising professional class in these cities wants contemporary, low-maintenance homes with generous storage and clear, honest pricing — a natural fit for our model.',
    designNotes: [
      'Bastar’s dhokra metal-casting and wrought-iron craft traditions offer unique lighting and hardware accents.',
      'Hot, dry summers mean heat-stable finishes and deep window treatments on west-facing rooms.',
      'Bhilai’s steel-plant townships have standardised housing plans that we know well.',
    ],
  },

  // ───────────────────────────── NORTHEAST ─────────────────────────────
  {
    slug: 'assam',
    name: 'Assam',
    kind: 'state',
    capital: 'Dispur',
    region: 'Northeast',
    languages: ['Assamese', 'Bengali'],
    districts: [
      'Bajali',
      'Baksa',
      'Barpeta',
      'Biswanath',
      'Bongaigaon',
      'Cachar',
      'Charaideo',
      'Chirang',
      'Darrang',
      'Dhemaji',
      'Dhubri',
      'Dibrugarh',
      'Dima Hasao',
      'Goalpara',
      'Golaghat',
      'Hailakandi',
      'Hojai',
      'Jorhat',
      'Kamrup',
      'Kamrup Metropolitan',
      'Karbi Anglong',
      'Kokrajhar',
      'Lakhimpur',
      'Majuli',
      'Morigaon',
      'Nagaon',
      'Nalbari',
      'Sivasagar',
      'Sonitpur',
      'South Salmara-Mankachar',
      'Sribhumi',
      'Tamulpur',
      'Tinsukia',
      'Udalguri',
      'West Karbi Anglong',
    ],
    intro:
      'Assam is the gateway to the Northeast and Guwahati its commercial capital — a fast-growing city where new apartments in Beltola, Six Mile and Zoo Road are replacing Assam-type bungalows. Being close to Kolkata, Guwahati is one of our most active markets outside West Bengal, and we also serve Dibrugarh, Jorhat, Silchar and Tezpur.',
    designNotes: [
      'Very high rainfall and humidity, plus seismic zone V, shape every specification: lightweight partitions, BWP boards and flexible fixings.',
      'Bamboo, cane and Muga silk are authentic Assamese materials we use for screens, furniture and upholstery.',
      'Traditional Assam-type houses inspire pitched wooden ceilings, verandas and breathable material palettes.',
    ],
  },
  {
    slug: 'meghalaya',
    name: 'Meghalaya',
    kind: 'state',
    capital: 'Shillong',
    region: 'Northeast',
    districts: [
      'East Garo Hills',
      'East Jaintia Hills',
      'East Khasi Hills',
      'Eastern West Khasi Hills',
      'North Garo Hills',
      'Ri Bhoi',
      'South Garo Hills',
      'South West Garo Hills',
      'South West Khasi Hills',
      'West Garo Hills',
      'West Jaintia Hills',
      'West Khasi Hills',
    ],
    intro:
      'Shillong’s colonial-era cottages, pine-clad hills and cool, wet climate give Meghalaya a distinctly European-hill-station character. We design cosy, insulated interiors for homes and homestays in Shillong and Tura that embrace timber, wool and warm lighting while managing the state’s record rainfall.',
    designNotes: [
      'Cherrapunji-level rainfall means damp-proofing, ventilated cavities and anti-fungal finishes are essential.',
      'Khasi cane and bamboo craft, and local pine, are authentic material choices.',
      'Cool temperatures allow fabric-heavy, layered interiors that would be impractical in the plains.',
    ],
  },
  {
    slug: 'manipur',
    name: 'Manipur',
    kind: 'state',
    capital: 'Imphal',
    region: 'Northeast',
    districts: [
      'Bishnupur',
      'Chandel',
      'Churachandpur',
      'Imphal East',
      'Imphal West',
      'Jiribam',
      'Kakching',
      'Kamjong',
      'Kangpokpi',
      'Noney',
      'Pherzawl',
      'Senapati',
      'Tamenglong',
      'Tengnoupal',
      'Thoubal',
      'Ukhrul',
    ],
    intro:
      'Imphal’s homes reflect Manipur’s rich textile and craft heritage — Meitei weaving, Longpi black pottery and cane work. We design contemporary interiors for the valley’s new apartments and independent homes with earthquake-conscious detailing and materials suited to the humid subtropical climate.',
    designNotes: [
      'Seismic zone V: lightweight, well-anchored joinery and flexible ceiling systems.',
      'Longpi pottery and Manipuri handloom bring authentic texture to accents.',
      'Mild climate allows generous use of natural wood and cane.',
    ],
  },
  {
    slug: 'tripura',
    name: 'Tripura',
    kind: 'state',
    capital: 'Agartala',
    region: 'Northeast',
    languages: ['Bengali'],
    districts: [
      'Dhalai',
      'Gomati',
      'Khowai',
      'North Tripura',
      'Sepahijala',
      'South Tripura',
      'Unakoti',
      'West Tripura',
    ],
    intro:
      'Agartala shares Kolkata’s Bengali sensibility and is well connected to our head office, making Tripura a natural extension of our West Bengal operations. We design homes and commercial spaces that use the state’s celebrated bamboo and cane craft with modern modular systems.',
    designNotes: [
      'Tripura bamboo and cane furniture is among India’s finest — a local, sustainable choice for accent pieces.',
      'Heavy monsoons require BWP boards and ventilated storage.',
      'Bengali-style layouts with a thakur ghar (pooja space) and open dining are common briefs.',
    ],
  },
  {
    slug: 'mizoram',
    name: 'Mizoram',
    kind: 'state',
    capital: 'Aizawl',
    region: 'Northeast',
    districts: [
      'Aizawl',
      'Champhai',
      'Hnahthial',
      'Khawzawl',
      'Kolasib',
      'Lawngtlai',
      'Lunglei',
      'Mamit',
      'Saitual',
      'Serchhip',
      'Siaha',
    ],
    intro:
      'Aizawl’s dramatic hillside homes are built on steep slopes with narrow access, so interiors must be modular, lightweight and cleverly stacked across split levels. We design compact, warm interiors with Mizo textile accents for the city’s tightly packed residential ridges.',
    designNotes: [
      'Steep sites and narrow roads mean everything is prefabricated in flat-pack form and assembled on site.',
      'Puan textiles offer bold, authentic patterns for upholstery and rugs.',
      'Split-level plans benefit from continuous flooring and unified lighting to feel cohesive.',
    ],
  },
  {
    slug: 'nagaland',
    name: 'Nagaland',
    kind: 'state',
    capital: 'Kohima',
    region: 'Northeast',
    districts: [
      'Chümoukedima',
      'Dimapur',
      'Kiphire',
      'Kohima',
      'Longleng',
      'Mokokchung',
      'Mon',
      'Niuland',
      'Noklak',
      'Peren',
      'Phek',
      'Shamator',
      'Tseminyü',
      'Tuensang',
      'Wokha',
      'Zünheboto',
    ],
    intro:
      'Dimapur, the commercial hub, and Kohima, the hill capital, anchor Nagaland’s growing residential market. Naga woodcarving, shawl weaving and bamboo craft give us a strong regional vocabulary, which we combine with modern kitchens, wardrobes and lighting.',
    designNotes: [
      'Kohima’s hill climate favours timber-heavy, insulated interiors; Dimapur’s plains climate is warmer and more humid.',
      'Naga morung-inspired carved motifs and woven textiles make distinctive feature elements.',
      'Seismic detailing and lightweight construction are standard.',
    ],
  },
  {
    slug: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    kind: 'state',
    capital: 'Itanagar',
    region: 'Northeast',
    districts: [
      'Anjaw',
      'Changlang',
      'Dibang Valley',
      'East Kameng',
      'East Siang',
      'Itanagar Capital Complex',
      'Kamle',
      'Kra Daadi',
      'Kurung Kumey',
      'Lepa Rada',
      'Lohit',
      'Longding',
      'Lower Dibang Valley',
      'Lower Siang',
      'Lower Subansiri',
      'Namsai',
      'Pakke-Kessang',
      'Papum Pare',
      'Shi Yomi',
      'Siang',
      'Tawang',
      'Tirap',
      'Upper Siang',
      'Upper Subansiri',
      'West Kameng',
      'West Siang',
    ],
    intro:
      'Itanagar and Naharlagun are Arunachal’s growing urban centres, with new government and private housing that needs practical, climate-appropriate interiors. We draw on the state’s bamboo, cane and Monpa woodcraft traditions for warmth and character.',
    designNotes: [
      'High rainfall and seismic activity dictate lightweight, moisture-resistant systems.',
      'Bamboo and cane are abundant, sustainable and locally crafted.',
      'Hill-town access requires flat-pack modular delivery.',
    ],
  },
  {
    slug: 'sikkim',
    name: 'Sikkim',
    kind: 'state',
    capital: 'Gangtok',
    region: 'Northeast',
    languages: ['Nepali'],
    districts: [
      'Gangtok',
      'Gyalshing',
      'Mangan',
      'Namchi',
      'Pakyong',
      'Soreng',
    ],
    intro:
      'Gangtok’s boutique hotels, homestays and hillside homes want warm, Himalayan-modern interiors — timber, wool, stone and Buddhist-inspired detailing — that also handle cold, damp winters. Sikkim is a short hop from Siliguri, which keeps our logistics efficient.',
    designNotes: [
      'Insulation, double glazing and wooden flooring with underlay are baseline specifications for Gangtok winters.',
      'Thangka art, prayer-wheel motifs and local wood carving inform accent details.',
      'Hospitality projects dominate; durable, photogenic finishes are prioritised.',
    ],
  },
];

export const STATE_BY_SLUG: Record<string, StateData> = Object.fromEntries(
  STATES.map((s) => [s.slug, s]),
);
