/**
 * Background video for the home page.
 *
 * The hero clip is remuxed for faststart (its index sits before the media
 * data), so the browser can begin playing as the file arrives instead of
 * waiting for the whole download.
 */
export const HERO_VIDEO = '/videos/hero.mp4';

/** The contact section at the foot of the page. Lazy-loaded when scrolled to. */
export const FOOTER_VIDEO = '/videos/OFFICE full_1.mp4';

/**
 * Generated by `npm run optimize:videos`. Left null until they exist — a
 * poster that 404s costs a request and shows nothing.
 */
export const HERO_VIDEO_POSTER: string | null = null;
export const FOOTER_VIDEO_POSTER: string | null = null;
