/**
 * Background video for the site.
 *
 * The hero at the top of the home page and the contact section on /contact
 * deliberately play the same clip: the browser downloads it once and the
 * second use is served from cache. Split them only if the two sections
 * should genuinely show different footage.
 *
 * Remuxed for faststart — the index sits before the media data, so playback
 * can begin as the file arrives rather than after the whole download.
 */
export const SITE_VIDEO = '/videos/hero.mp4';

export const HERO_VIDEO = SITE_VIDEO;
export const FOOTER_VIDEO = SITE_VIDEO;

/**
 * Generated by `npm run optimize:videos`. Left null until it exists — a
 * poster that 404s costs a request and shows nothing.
 */
export const SITE_VIDEO_POSTER: string | null = null;

export const HERO_VIDEO_POSTER = SITE_VIDEO_POSTER;
export const FOOTER_VIDEO_POSTER = SITE_VIDEO_POSTER;
