/**
 * The home page's background video, shared by the hero at the top and the
 * contact section at the bottom.
 *
 * Deliberately the same file in both places: the browser downloads it once
 * and the footer's lazy loader then hits cache, so the second use is free.
 * Pointing them at different clips would mean shipping two videos.
 */
export const HOME_VIDEO = '/videos/OFFICE full_1.mp4';

/**
 * Generated by `npm run optimize:videos`. Left null until it exists — a
 * poster that 404s costs a request and shows nothing.
 */
export const HOME_VIDEO_POSTER: string | null = null;
