import type { CityData } from '../types';

export const CENTRAL_CITIES: CityData[] = [
  // ── Madhya Pradesh ──
  {
    slug: 'indore',
    name: 'Indore',
    state: 'madhya-pradesh',
    district: 'Indore',
    tier: 1,
    localities: [
      'Vijay Nagar',
      'Scheme 54',
      'Scheme 78',
      'AB Road',
      'Bicholi Mardana',
      'Super Corridor',
      'Rau',
      'Palasia',
      'Saket Nagar',
      'Sudama Nagar',
      'Mahalaxmi Nagar',
      'Nipania',
      'Bypass Road',
      'Old Palasia',
      'Khajrana',
      'Silicon City',
    ],
    landmarks: ['Rajwada', 'Lal Bagh Palace', 'Sarafa Bazaar'],
    climate: 'hot-dry',
    housing: ['independent', 'gated-villa', 'high-rise'],
    housingNote:
      'India’s cleanest city has a strong villa-plot culture in Vijay Nagar and Bicholi Mardana and rising towers on the Super Corridor and AB Road.',
    styleNote:
      'Indore families love generous, warm interiors — big kitchens, celebratory living rooms and rich wood tones.',
    priceIndex: 0.95,
    nearby: ['bhopal', 'ujjain', 'ahmedabad'],
    geo: { lat: 22.7196, lng: 75.8577 },
  },
  {
    slug: 'bhopal',
    name: 'Bhopal',
    state: 'madhya-pradesh',
    district: 'Bhopal',
    tier: 2,
    localities: [
      'Arera Colony',
      'Shahpura',
      'MP Nagar',
      'Kolar Road',
      'Hoshangabad Road',
      'Bawadiya Kalan',
      'Ayodhya Bypass',
      'Chunabhatti',
      'Misrod',
      'Gulmohar',
      'Shyamla Hills',
      'Katara Hills',
      'Lalghati',
    ],
    landmarks: ['Upper Lake', 'Taj-ul-Masajid', 'Van Vihar'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'The City of Lakes has leafy bungalow colonies (Arera, Shahpura, Shyamla Hills) and new apartment corridors on Hoshangabad and Kolar Roads.',
    styleNote:
      'Gond art and Chanderi and Maheshwari weaves give Bhopal homes an authentic Madhya Pradesh identity.',
    priceIndex: 0.92,
    nearby: ['indore', 'jabalpur', 'nagpur'],
    geo: { lat: 23.2599, lng: 77.4126 },
  },
  {
    slug: 'jabalpur',
    name: 'Jabalpur',
    state: 'madhya-pradesh',
    district: 'Jabalpur',
    tier: 2,
    localities: [
      'Napier Town',
      'Wright Town',
      'Civil Lines',
      'Vijay Nagar',
      'Gorakhpur',
      'Madan Mahal',
      'Adhartal',
      'Ranjhi',
      'Katanga',
      'Tilhari',
    ],
    landmarks: [
      'Bhedaghat Marble Rocks',
      'Dhuandhar Falls',
      'Madan Mahal Fort',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A defence and judicial city with colonial-era Civil Lines bungalows and new towers in Vijay Nagar and Tilhari.',
    styleNote:
      'Local Bhedaghat marble makes stone-rich interiors especially cost-effective.',
    priceIndex: 0.9,
    nearby: ['bhopal', 'nagpur', 'raipur'],
    geo: { lat: 23.1815, lng: 79.9864 },
  },
  {
    slug: 'gwalior',
    name: 'Gwalior',
    state: 'madhya-pradesh',
    district: 'Gwalior',
    tier: 2,
    localities: [
      'City Centre',
      'Thatipur',
      'Morar',
      'Lashkar',
      'Vinay Nagar',
      'DD Nagar',
      'Gola Ka Mandir',
      'Shivpuri Link Road',
      'Mahalgaon',
      'Deendayal Nagar',
    ],
    landmarks: ['Gwalior Fort', 'Jai Vilas Palace', 'Sun Temple'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage', 'high-rise'],
    housingNote:
      'A royal city with Scindia-era heritage and modern colonies in City Centre and Thatipur.',
    styleNote:
      'Gwalior’s stone-carving heritage and Chanderi weaves inspire dignified, classic interiors.',
    priceIndex: 0.9,
    nearby: ['agra', 'jhansi', 'bhopal'],
    geo: { lat: 26.2183, lng: 78.1828 },
  },
  {
    slug: 'ujjain',
    name: 'Ujjain',
    state: 'madhya-pradesh',
    district: 'Ujjain',
    tier: 3,
    localities: [
      'Freeganj',
      'Nanakheda',
      'Dewas Road',
      'Mahakal Area',
      'Rishi Nagar',
      'Indira Nagar',
      'Agar Road',
    ],
    landmarks: ['Mahakaleshwar Temple', 'Mahakal Lok', 'Ram Ghat'],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'Mahakal Lok has driven a hospitality boom alongside family homes in Freeganj and Nanakheda.',
    styleNote: 'Temple-town serenity with sandstone and brass accents.',
    priceIndex: 0.88,
    nearby: ['indore', 'bhopal'],
    geo: { lat: 23.1765, lng: 75.7885 },
  },

  // ── Chhattisgarh ──
  {
    slug: 'raipur',
    name: 'Raipur',
    state: 'chhattisgarh',
    district: 'Raipur',
    tier: 2,
    localities: [
      'Shankar Nagar',
      'Civil Lines',
      'Devendra Nagar',
      'Pandri',
      'Samta Colony',
      'Telibandha',
      'VIP Road',
      'Avanti Vihar',
      'Nava Raipur (Atal Nagar)',
      'Kamal Vihar',
      'Amlidih',
      'Daldal Seoni',
      'Mowa',
      'Saddu',
    ],
    landmarks: [
      'Marine Drive Telibandha',
      'Purkhouti Muktangan',
      'Nava Raipur',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Raipur’s VIP Road, Kamal Vihar and the planned Nava Raipur are the state’s fastest-growing residential belts.',
    styleNote:
      'Bastar dhokra metalwork and wrought iron are unique regional accents for lighting and hardware.',
    priceIndex: 0.9,
    nearby: ['bhilai', 'bilaspur', 'nagpur'],
    geo: { lat: 21.2514, lng: 81.6296 },
  },
  {
    slug: 'bhilai',
    name: 'Bhilai',
    state: 'chhattisgarh',
    district: 'Durg',
    tier: 3,
    aka: ['Durg'],
    localities: [
      'Sector 1–10',
      'Nehru Nagar',
      'Smriti Nagar',
      'Risali',
      'Supela',
      'Junwani',
      'Durg',
      'Kohka',
      'Vaishali Nagar',
    ],
    landmarks: ['Bhilai Steel Plant', 'Maitri Bagh', 'IIT Bhilai'],
    climate: 'hot-dry',
    housing: ['row-house', 'independent', 'high-rise'],
    housingNote:
      'A steel township with sector quarters and a private market in Nehru Nagar and Smriti Nagar.',
    styleNote:
      'Retrofitting standard township plans with modern modular kitchens is a Bhilai speciality.',
    priceIndex: 0.88,
    nearby: ['raipur', 'bilaspur'],
    geo: { lat: 21.2094, lng: 81.4285 },
  },
  {
    slug: 'bilaspur',
    name: 'Bilaspur',
    state: 'chhattisgarh',
    district: 'Bilaspur',
    tier: 3,
    localities: [
      'Vyapar Vihar',
      'Sarkanda',
      'Mangla',
      'Nehru Nagar',
      'Rajkishore Nagar',
      'Torwa',
      'Tifra',
      'Ashok Nagar',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'Chhattisgarh’s judicial capital and railway hub has independent homes in Vyapar Vihar and new colonies toward Mangla.',
    styleNote:
      'Kosa silk from nearby Champa is a beautiful local textile for upholstery.',
    priceIndex: 0.87,
    nearby: ['raipur', 'bhilai'],
    geo: { lat: 22.0797, lng: 82.1409 },
  },
];
