import type { CityData } from '../types';

export const EAST_CITIES: CityData[] = [
  // ── West Bengal ──
  {
    slug: 'kolkata',
    name: 'Kolkata',
    state: 'west-bengal',
    district: 'Kolkata',
    tier: 1,
    aka: ['Calcutta'],
    localities: [
      'Ballygunge',
      'Alipore',
      'Salt Lake (Bidhannagar)',
      'New Town',
      'Rajarhat',
      'Park Street',
      'Bhowanipore',
      'Tollygunge',
      'Jadavpur',
      'Behala',
      'Garia',
      'Joka',
      'Tangra',
      'EM Bypass',
      'Lake Town',
      'Dum Dum',
      'Southern Avenue',
    ],
    landmarks: [
      'Victoria Memorial',
      'Howrah Bridge',
      'Park Street',
      'Eco Park',
    ],
    climate: 'humid-coastal',
    housing: ['high-rise', 'heritage', 'independent', 'mixed'],
    housingNote:
      'Kolkata mixes heritage bungalows and 1960s–80s cooperative flats in the south with modern high-rise townships along EM Bypass, New Town and Rajarhat. Redevelopment of old plots into boutique 4–6 storey buildings is common in Ballygunge and Alipore.',
    styleNote:
      'The city has a deep cultural design memory — red-oxide floors, louvred green shutters, Burma teak and cane — that we reinterpret with clean contemporary lines.',
    marketNote:
      'Our workshop and head office in Tangra let us deliver Kolkata projects with the shortest lead times anywhere in our network.',
    priceIndex: 1,
    nearby: ['howrah', 'barrackpore', 'durgapur', 'kharagpur', 'siliguri'],
    geo: { lat: 22.5726, lng: 88.3639 },
  },
  {
    slug: 'howrah',
    name: 'Howrah',
    state: 'west-bengal',
    district: 'Howrah',
    tier: 2,
    localities: [
      'Shibpur',
      'Salkia',
      'Liluah',
      'Bally',
      'Santragachi',
      'Andul',
      'Kadamtala',
      'Belur',
      'Domjur',
      'Uluberia',
    ],
    landmarks: ['Howrah Bridge', 'Belur Math', 'Indian Botanic Garden'],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed', 'high-rise'],
    housingNote:
      'Howrah has a strong stock of self-built independent homes on narrow plots alongside newer apartment projects near Santragachi, Andul Road and the Kona Expressway.',
    styleNote:
      'Clients value robust, practical interiors — heavy-duty kitchens, large storage and simple, elegant living rooms.',
    priceIndex: 0.95,
    nearby: ['kolkata', 'barrackpore', 'kharagpur'],
    geo: { lat: 22.5958, lng: 88.2636 },
  },
  {
    slug: 'siliguri',
    name: 'Siliguri',
    state: 'west-bengal',
    district: 'Darjeeling',
    tier: 2,
    localities: [
      'Sevoke Road',
      'Hakim Para',
      'Pradhan Nagar',
      'Matigara',
      'Salugara',
      'Bagdogra',
      'Hill Cart Road',
      'Uttorayon Township',
      'Champasari',
      'Dabgram',
    ],
    landmarks: [
      'Sevoke Coronation Bridge',
      'ISKCON Siliguri',
      'Bagdogra Airport',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Siliguri is the gateway to Darjeeling, Sikkim and the Northeast, and its Sevoke Road and Matigara belts are seeing rapid apartment and township growth (Uttorayon, City Centre).',
    styleNote:
      'Buyers here want warm, wood-forward interiors that nod to the nearby hills, paired with modern kitchens.',
    marketNote:
      'Siliguri is our staging base for Darjeeling, Gangtok and Dooars projects.',
    priceIndex: 0.95,
    nearby: ['darjeeling', 'gangtok', 'jalpaiguri', 'kolkata'],
    geo: { lat: 26.7271, lng: 88.3953 },
  },
  {
    slug: 'darjeeling',
    name: 'Darjeeling',
    state: 'west-bengal',
    district: 'Darjeeling',
    tier: 3,
    localities: [
      'Chowrasta',
      'Mall Road',
      'Lebong',
      'Ghoom',
      'Jorebungalow',
      'Kurseong',
      'Mirik',
    ],
    landmarks: ['Tiger Hill', 'Batasia Loop', 'Darjeeling Himalayan Railway'],
    climate: 'cold-hill',
    housing: ['heritage', 'independent'],
    housingNote:
      'Darjeeling’s colonial-era bungalows, tea-estate homes and boutique hotels dominate the brief, most on steep sites with tight access.',
    styleNote:
      'We design cosy, insulated spaces with timber panelling, wool textiles and views framed from every room.',
    priceIndex: 1.1,
    nearby: ['siliguri', 'gangtok'],
    geo: { lat: 27.036, lng: 88.2627 },
  },
  {
    slug: 'durgapur',
    name: 'Durgapur',
    state: 'west-bengal',
    district: 'Paschim Bardhaman',
    tier: 2,
    localities: [
      'City Centre',
      'Bidhannagar',
      'Benachity',
      'A-Zone',
      'B-Zone',
      'Muchipara',
      'Fuljhore',
      'Gopalmath',
    ],
    landmarks: ['Durgapur Barrage', 'Junction Mall', 'NIT Durgapur'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'row-house'],
    housingNote:
      'A planned steel city with a growing IT and education population, Durgapur has orderly plotted neighbourhoods and new apartment projects near City Centre and Bidhannagar.',
    styleNote:
      'Clients lean toward contemporary, clutter-free interiors with high-quality modular kitchens.',
    priceIndex: 0.9,
    nearby: ['asansol', 'bardhaman', 'kolkata'],
    geo: { lat: 23.5204, lng: 87.3119 },
  },
  {
    slug: 'asansol',
    name: 'Asansol',
    state: 'west-bengal',
    district: 'Paschim Bardhaman',
    tier: 2,
    localities: [
      'Burnpur',
      'Kulti',
      'Ushagram',
      'Sen Raleigh Road',
      'Hutton Road',
      'GT Road',
      'Raniganj',
      'Jamuria',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'Asansol’s industrial heritage means many company colonies and large independent homes; new apartments are rising along GT Road and toward Burnpur.',
    styleNote:
      'Durable, classic interiors with generous storage are the typical brief.',
    priceIndex: 0.9,
    nearby: ['durgapur', 'dhanbad', 'bardhaman'],
    geo: { lat: 23.6739, lng: 86.9524 },
  },
  {
    slug: 'bardhaman',
    name: 'Bardhaman',
    state: 'west-bengal',
    district: 'Purba Bardhaman',
    tier: 3,
    aka: ['Burdwan'],
    localities: [
      'Curzon Gate',
      'GT Road',
      'Nabbabhat',
      'Golapbag',
      'Ullas',
      'Kalna Road',
      'Baburbag',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'A university and agricultural trading town with predominantly independent houses and a growing set of mid-rise apartments along GT Road.',
    styleNote:
      'Understated, family-oriented interiors with traditional touches suit local tastes.',
    priceIndex: 0.88,
    nearby: ['durgapur', 'asansol', 'kolkata'],
    geo: { lat: 23.2324, lng: 87.8615 },
  },
  {
    slug: 'kharagpur',
    name: 'Kharagpur',
    state: 'west-bengal',
    district: 'Paschim Medinipur',
    tier: 3,
    localities: [
      'IIT Kharagpur Campus',
      'Inda',
      'Gole Bazar',
      'Talbagicha',
      'Hijli',
      'Nimpura',
      'Midnapore',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'Home to IIT Kharagpur and a major railway hub, the town has faculty housing, railway colonies and independent homes.',
    styleNote:
      'Practical, study-friendly interiors with good lighting and storage are common requests.',
    priceIndex: 0.88,
    nearby: ['kolkata', 'howrah', 'haldia'],
    geo: { lat: 22.346, lng: 87.232 },
  },
  {
    slug: 'haldia',
    name: 'Haldia',
    state: 'west-bengal',
    district: 'Purba Medinipur',
    tier: 3,
    localities: [
      'Durgachak',
      'Township',
      'Haldia Port Area',
      'Sutahata',
      'Brajalalchak',
      'Mahishadal',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'A port and petrochemical town with company townships and new independent homes for a professional workforce.',
    styleNote:
      'Low-maintenance, corrosion-resistant interiors are essential in this coastal industrial setting.',
    priceIndex: 0.9,
    nearby: ['kharagpur', 'kolkata'],
    geo: { lat: 22.0667, lng: 88.0698 },
  },
  {
    slug: 'barrackpore',
    name: 'Barrackpore',
    state: 'west-bengal',
    district: 'North 24 Parganas',
    tier: 3,
    localities: [
      'Barrackpore Cantonment',
      'Titagarh',
      'Khardah',
      'Sodepur',
      'Ichapur',
      'Shyamnagar',
      'Naihati',
      'Barasat',
      'Madhyamgram',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed', 'high-rise'],
    housingNote:
      'The northern suburbs of Kolkata — Barrackpore, Sodepur, Barasat, Madhyamgram — are dense with independent homes and new mid-rise apartments along BT Road and Jessore Road.',
    styleNote:
      'Space-efficient planning for compact 2BHK flats is the most frequent brief.',
    priceIndex: 0.95,
    nearby: ['kolkata', 'howrah'],
    geo: { lat: 22.7642, lng: 88.3776 },
  },
  {
    slug: 'jalpaiguri',
    name: 'Jalpaiguri',
    state: 'west-bengal',
    district: 'Jalpaiguri',
    tier: 3,
    localities: [
      'Kadamtala',
      'Hakimpara',
      'Dinbazar',
      'Racecourse Para',
      'Pandapara',
      'Mohitnagar',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'A tea and administrative town at the foothills of the Dooars, Jalpaiguri has mostly independent homes with large plots.',
    styleNote:
      'Wood-rich, veranda-centred interiors suit the region’s climate and heritage.',
    priceIndex: 0.9,
    nearby: ['siliguri', 'darjeeling'],
    geo: { lat: 26.5215, lng: 88.7196 },
  },

  // ── Odisha ──
  {
    slug: 'bhubaneswar',
    name: 'Bhubaneswar',
    state: 'odisha',
    district: 'Khordha',
    tier: 1,
    localities: [
      'Patia',
      'Chandrasekharpur',
      'Nayapalli',
      'Saheed Nagar',
      'Jaydev Vihar',
      'Khandagiri',
      'Sundarpada',
      'Infocity',
      'Kalinga Nagar',
      'Old Town',
      'Rasulgarh',
      'Tamando',
    ],
    landmarks: ['Lingaraj Temple', 'Kalinga Stadium', 'Infocity'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'gated-villa', 'independent'],
    housingNote:
      'A planned capital with generous plots in Nayapalli and Saheed Nagar and fast-growing apartment corridors in Patia, Chandrasekharpur and near Infocity.',
    styleNote:
      'Buyers like temple-inspired warmth — Khondalite stone, brass and earthy palettes — with modern open plans.',
    priceIndex: 0.93,
    nearby: ['cuttack', 'puri', 'rourkela', 'kolkata'],
    geo: { lat: 20.2961, lng: 85.8245 },
  },
  {
    slug: 'cuttack',
    name: 'Cuttack',
    state: 'odisha',
    district: 'Cuttack',
    tier: 2,
    localities: [
      'Buxi Bazar',
      'Badambadi',
      'CDA (Cuttack Development Authority)',
      'Bidanasi',
      'Link Road',
      'Chauliaganj',
      'Tulsipur',
      'Jobra',
    ],
    landmarks: ['Barabati Fort', 'Netaji Birth Place Museum'],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed', 'high-rise'],
    housingNote:
      'Odisha’s old capital has dense heritage neighbourhoods and newer planned sectors in CDA and Bidanasi.',
    styleNote:
      'Silver filigree (tarakasi) is Cuttack’s signature craft — a perfect accent for lighting and hardware details.',
    priceIndex: 0.9,
    nearby: ['bhubaneswar', 'puri'],
    geo: { lat: 20.4625, lng: 85.883 },
  },
  {
    slug: 'puri',
    name: 'Puri',
    state: 'odisha',
    district: 'Puri',
    tier: 3,
    localities: [
      'Grand Road',
      'Swargadwar',
      'Chakratirtha',
      'Baliapanda',
      'Marine Drive',
      'VIP Road',
      'Konark Road',
    ],
    landmarks: ['Jagannath Temple', 'Puri Beach', 'Konark Sun Temple'],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'Puri’s demand is a mix of holiday homes, guesthouses and boutique hotels near Marine Drive and the Konark corridor.',
    styleNote:
      'Pattachitra art, sea-facing verandas and salt-proof finishes define our Puri projects.',
    priceIndex: 0.92,
    nearby: ['bhubaneswar', 'cuttack'],
    geo: { lat: 19.8135, lng: 85.8312 },
  },
  {
    slug: 'rourkela',
    name: 'Rourkela',
    state: 'odisha',
    district: 'Sundargarh',
    tier: 2,
    localities: [
      'Civil Township',
      'Sector 2',
      'Sector 19',
      'Koel Nagar',
      'Panposh',
      'Chhend Colony',
      'Basanti Colony',
      'Udit Nagar',
    ],
    landmarks: [
      'Rourkela Steel Plant',
      'NIT Rourkela',
      'Birsa Munda Hockey Stadium',
    ],
    climate: 'composite',
    housing: ['independent', 'row-house', 'mixed'],
    housingNote:
      'A steel-plant township with sector-based planning, Rourkela has consistent housing plans and a growing independent-home market in Chhend and Koel Nagar.',
    styleNote:
      'Clean, functional interiors with robust kitchens suit the city’s engineering culture.',
    priceIndex: 0.9,
    nearby: ['bhubaneswar', 'sambalpur', 'ranchi'],
    geo: { lat: 22.2604, lng: 84.8536 },
  },
  {
    slug: 'sambalpur',
    name: 'Sambalpur',
    state: 'odisha',
    district: 'Sambalpur',
    tier: 3,
    localities: [
      'Budharaja',
      'Ainthapali',
      'Modipara',
      'Dhanupali',
      'Burla',
      'Hirakud',
      'Remed',
    ],
    landmarks: ['Hirakud Dam', 'Samaleswari Temple'],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'Western Odisha’s largest city, with independent homes and new apartments near Ainthapali and Burla.',
    styleNote:
      'Sambalpuri ikat is a world-famous local textile that we use in upholstery and accent panels.',
    priceIndex: 0.88,
    nearby: ['rourkela', 'bhubaneswar'],
    geo: { lat: 21.4669, lng: 83.9812 },
  },
  {
    slug: 'berhampur',
    name: 'Berhampur',
    state: 'odisha',
    district: 'Ganjam',
    tier: 3,
    aka: ['Brahmapur'],
    localities: [
      'Gandhi Nagar',
      'Lanjipalli',
      'Ambapua',
      'Gosaninuagaon',
      'Bijipur',
      'Hillpatna',
      'Gopalpur',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'The silk city of Odisha has a strong independent-home culture and beach-facing second homes at nearby Gopalpur.',
    styleNote:
      'Berhampuri silk and brass form part of our regional accent palette here.',
    priceIndex: 0.88,
    nearby: ['bhubaneswar', 'visakhapatnam'],
    geo: { lat: 19.3149, lng: 84.7941 },
  },

  // ── Bihar ──
  {
    slug: 'patna',
    name: 'Patna',
    state: 'bihar',
    district: 'Patna',
    tier: 1,
    localities: [
      'Boring Road',
      'Kankarbagh',
      'Bailey Road',
      'Rajendra Nagar',
      'Patliputra Colony',
      'Danapur',
      'Anisabad',
      'Gola Road',
      'Fraser Road',
      'Saguna More',
      'Kidwaipuri',
      'Exhibition Road',
    ],
    landmarks: ['Golghar', 'Patna Sahib', 'Buddha Smriti Park'],
    climate: 'composite',
    housing: ['high-rise', 'independent', 'mixed'],
    housingNote:
      'Patna is shifting from large independent houses in Patliputra Colony and Boring Road to new apartment towers along Bailey Road, Danapur and Kankarbagh.',
    styleNote:
      'Families want generous multi-generational layouts — separate pooja rooms, big dining areas and durable finishes.',
    priceIndex: 0.9,
    nearby: ['gaya', 'muzaffarpur', 'ranchi', 'varanasi'],
    geo: { lat: 25.5941, lng: 85.1376 },
  },
  {
    slug: 'gaya',
    name: 'Gaya',
    state: 'bihar',
    district: 'Gaya',
    tier: 3,
    localities: [
      'AP Colony',
      'Magadh Colony',
      'Civil Lines',
      'Bodh Gaya',
      'Delha',
      'GB Road',
      'Kotwali',
    ],
    landmarks: ['Mahabodhi Temple', 'Vishnupad Temple'],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'Gaya and neighbouring Bodh Gaya have a strong hospitality demand from pilgrims alongside independent family homes.',
    styleNote:
      'Calm, meditative palettes inspired by Bodh Gaya’s Buddhist heritage suit both homes and guesthouses.',
    priceIndex: 0.87,
    nearby: ['patna'],
    geo: { lat: 24.7955, lng: 85.0002 },
  },
  {
    slug: 'muzaffarpur',
    name: 'Muzaffarpur',
    state: 'bihar',
    district: 'Muzaffarpur',
    tier: 3,
    localities: [
      'Mithanpura',
      'Aghoria Bazar',
      'Bhagwanpur',
      'Juran Chapra',
      'Kalambagh Road',
      'Ramna',
      'Brahmpura',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'North Bihar’s commercial hub is dominated by independent homes, with new apartments emerging along Kalambagh Road and Bhagwanpur.',
    styleNote:
      'Madhubani art is a nearby regional treasure we integrate into accent walls.',
    priceIndex: 0.87,
    nearby: ['patna', 'darbhanga'],
    geo: { lat: 26.1209, lng: 85.3647 },
  },
  {
    slug: 'darbhanga',
    name: 'Darbhanga',
    state: 'bihar',
    district: 'Darbhanga',
    tier: 3,
    localities: [
      'Laheriasarai',
      'Allalpatti',
      'Benta',
      'Kathalbari',
      'Donar',
      'Bela',
    ],
    landmarks: ['Darbhanga Raj Fort', 'Shyama Mai Temple'],
    climate: 'composite',
    housing: ['independent', 'heritage', 'mixed'],
    housingNote:
      'The cultural capital of Mithila has heritage homes tied to the Darbhanga Raj legacy and new independent houses with large plots.',
    styleNote:
      'Mithila painting is native here — our accent walls and textiles draw directly on local artists.',
    priceIndex: 0.86,
    nearby: ['muzaffarpur', 'patna'],
    geo: { lat: 26.1542, lng: 85.8918 },
  },
  {
    slug: 'bhagalpur',
    name: 'Bhagalpur',
    state: 'bihar',
    district: 'Bhagalpur',
    tier: 3,
    localities: [
      'Tilka Manjhi',
      'Adampur',
      'Barari',
      'Nathnagar',
      'Sabour',
      'Zero Mile',
      'Mayaganj',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'The silk city on the Ganga has a university-town character with independent homes and emerging apartments near Zero Mile.',
    styleNote:
      'Bhagalpuri tussar silk is a natural local choice for drapery and upholstery accents.',
    priceIndex: 0.86,
    nearby: ['patna'],
    geo: { lat: 25.2425, lng: 86.9842 },
  },

  // ── Jharkhand ──
  {
    slug: 'ranchi',
    name: 'Ranchi',
    state: 'jharkhand',
    district: 'Ranchi',
    tier: 2,
    localities: [
      'Lalpur',
      'Kanke Road',
      'Harmu',
      'Bariatu',
      'Doranda',
      'Hinoo',
      'Ashok Nagar',
      'Morabadi',
      'Ratu Road',
      'Dhurwa',
      'Pundag',
      'Argora',
    ],
    landmarks: [
      'Rock Garden',
      'Jagannath Temple Ranchi',
      'Birsa Munda Airport',
    ],
    climate: 'moderate',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Ranchi’s plateau setting gives it a pleasant climate and a mix of independent homes in Harmu and Ashok Nagar with new towers along Kanke Road and Pundag.',
    styleNote:
      'Sohrai and Khovar tribal art motifs give Ranchi homes an authentic regional identity.',
    priceIndex: 0.92,
    nearby: ['jamshedpur', 'dhanbad', 'bokaro', 'kolkata'],
    geo: { lat: 23.3441, lng: 85.3096 },
  },
  {
    slug: 'jamshedpur',
    name: 'Jamshedpur',
    state: 'jharkhand',
    district: 'East Singhbhum',
    tier: 2,
    aka: ['Tatanagar'],
    localities: [
      'Bistupur',
      'Sakchi',
      'Kadma',
      'Sonari',
      'Telco Colony',
      'Mango',
      'Adityapur',
      'Golmuri',
      'Baridih',
      'Sidhgora',
    ],
    landmarks: ['Jubilee Park', 'Tata Steel Works', 'Dimna Lake'],
    climate: 'composite',
    housing: ['row-house', 'independent', 'high-rise'],
    housingNote:
      'India’s first planned industrial city has consistent Tata-township housing in Kadma, Sonari and Telco, plus private apartments in Mango and Adityapur.',
    styleNote:
      'Engineered precision and low-maintenance finishes resonate with Jamshedpur’s professional families.',
    priceIndex: 0.92,
    nearby: ['ranchi', 'kolkata', 'kharagpur'],
    geo: { lat: 22.8046, lng: 86.2029 },
  },
  {
    slug: 'dhanbad',
    name: 'Dhanbad',
    state: 'jharkhand',
    district: 'Dhanbad',
    tier: 2,
    localities: [
      'Bank More',
      'Hirapur',
      'Saraidhela',
      'Bartand',
      'Jharia',
      'Koyla Nagar',
      'Dhaiya',
      'Bhuli',
    ],
    landmarks: ['IIT (ISM) Dhanbad', 'Maithon Dam'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'mixed'],
    housingNote:
      'The coal capital has substantial independent homes in Hirapur and Saraidhela and new apartments rising near Bank More.',
    styleNote:
      'Dust-resistant, easy-clean finishes and strong ventilation planning are priorities here.',
    priceIndex: 0.9,
    nearby: ['bokaro', 'asansol', 'ranchi'],
    geo: { lat: 23.7957, lng: 86.4304 },
  },
  {
    slug: 'bokaro',
    name: 'Bokaro Steel City',
    state: 'jharkhand',
    district: 'Bokaro',
    tier: 3,
    aka: ['Bokaro'],
    localities: [
      'Sector 4',
      'Sector 5',
      'Sector 12',
      'City Centre',
      'Chas',
      'Co-operative Colony',
      'Ritudih',
    ],
    landmarks: ['Bokaro Steel Plant', 'City Park', 'Garga Dam'],
    climate: 'composite',
    housing: ['row-house', 'independent'],
    housingNote:
      'A sector-planned steel township with standardised quarters and a private-home market in Chas and Co-operative Colony.',
    styleNote:
      'We often retrofit older sector quarters with modular kitchens and full-height storage.',
    priceIndex: 0.9,
    nearby: ['dhanbad', 'ranchi'],
    geo: { lat: 23.6693, lng: 86.1511 },
  },
];
