import type { CityData } from '../types';

export const NORTHEAST_CITIES: CityData[] = [
  {
    slug: 'guwahati',
    name: 'Guwahati',
    state: 'assam',
    district: 'Kamrup Metropolitan',
    tier: 1,
    localities: [
      'Beltola',
      'Six Mile',
      'Zoo Road',
      'Dispur',
      'Ganeshguri',
      'Christian Basti',
      'Uzan Bazar',
      'Panbazar',
      'Bhangagarh',
      'Kahilipara',
      'Lokhra',
      'Hatigaon',
      'Maligaon',
      'Chandmari',
      'Bora Service',
      'GS Road',
      'Khanapara',
      'Azara',
    ],
    landmarks: ['Kamakhya Temple', 'Brahmaputra Riverfront', 'Umananda'],
    climate: 'tropical-wet',
    housing: ['high-rise', 'independent', 'mixed'],
    housingNote:
      'The Northeast’s commercial capital is shifting from Assam-type bungalows to apartment towers in Beltola, Six Mile and along GS Road.',
    styleNote:
      'Bamboo, cane and Muga silk are authentic Assamese materials we bring into screens, furniture and upholstery.',
    marketNote:
      'Seismic zone V and heavy rain mean lightweight partitions, BWP boards and flexible fixings in every specification.',
    priceIndex: 1.0,
    nearby: ['shillong', 'siliguri', 'kolkata', 'dibrugarh'],
    geo: { lat: 26.1445, lng: 91.7362 },
  },
  {
    slug: 'dibrugarh',
    name: 'Dibrugarh',
    state: 'assam',
    district: 'Dibrugarh',
    tier: 3,
    localities: [
      'Chowkidinghee',
      'Mancotta Road',
      'Jalan Nagar',
      'Graham Bazar',
      'Milan Nagar',
      'AT Road',
      'Duliajan',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'The tea capital of Assam has planter bungalows and new apartments along Mancotta Road.',
    styleNote:
      'Tea-estate heritage — verandas, timber floors, cane furniture — is the natural design language.',
    priceIndex: 0.95,
    nearby: ['guwahati', 'jorhat'],
    geo: { lat: 27.4728, lng: 94.912 },
  },
  {
    slug: 'jorhat',
    name: 'Jorhat',
    state: 'assam',
    district: 'Jorhat',
    tier: 3,
    localities: [
      'Gar-Ali',
      'AT Road',
      'Tarajan',
      'Club Road',
      'Baruah Chuk',
      'Cinnamara',
      'Titabor',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'A cultural and tea-research town with elegant independent homes.',
    styleNote: 'Assamese craft and warm timber define Jorhat interiors.',
    priceIndex: 0.93,
    nearby: ['dibrugarh', 'guwahati'],
    geo: { lat: 26.7509, lng: 94.2037 },
  },
  {
    slug: 'silchar',
    name: 'Silchar',
    state: 'assam',
    district: 'Cachar',
    tier: 3,
    localities: [
      'Tarapur',
      'Ambicapatty',
      'Meherpur',
      'Rangirkhari',
      'Link Road',
      'Sonai Road',
      'Itkhola',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'Barak Valley’s hub shares Bengal’s design sensibility and has a strong independent-home market.',
    styleNote:
      'Bengali-style layouts with a thakur ghar and open dining are typical briefs.',
    priceIndex: 0.93,
    nearby: ['guwahati', 'agartala'],
    geo: { lat: 24.8333, lng: 92.7789 },
  },
  {
    slug: 'shillong',
    name: 'Shillong',
    state: 'meghalaya',
    district: 'East Khasi Hills',
    tier: 2,
    localities: [
      'Laitumkhrah',
      'Nongthymmai',
      'Police Bazar',
      'Upper Shillong',
      'Lachumiere',
      'Malki',
      'Rynjah',
      'Dhankheti',
      'Mawlai',
      'Umpling',
      'Laban',
    ],
    landmarks: ['Ward’s Lake', 'Shillong Peak', 'Elephant Falls'],
    climate: 'cold-hill',
    housing: ['independent', 'heritage', 'mixed'],
    housingNote:
      'Colonial-era cottages and pine-clad homestays across Laitumkhrah and Upper Shillong.',
    styleNote:
      'Cosy, layered, European-hill-station interiors with local pine, cane and wool.',
    priceIndex: 1.05,
    nearby: ['guwahati'],
    geo: { lat: 25.5788, lng: 91.8933 },
  },
  {
    slug: 'agartala',
    name: 'Agartala',
    state: 'tripura',
    district: 'West Tripura',
    tier: 2,
    localities: [
      'Krishna Nagar',
      'Banamalipur',
      'Ramnagar',
      'Dhaleswar',
      'Abhoynagar',
      'Bardowali',
      'Kunjaban',
      'Indranagar',
      'Badharghat',
      'Pratapgarh',
    ],
    landmarks: ['Ujjayanta Palace', 'Neermahal'],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed', 'high-rise'],
    housingNote:
      'Agartala shares Kolkata’s Bengali sensibility and is one of our most connected Northeast markets.',
    styleNote:
      'Tripura’s bamboo and cane furniture is among India’s finest and features in our accent pieces.',
    priceIndex: 0.95,
    nearby: ['kolkata', 'silchar', 'guwahati'],
    geo: { lat: 23.8315, lng: 91.2868 },
  },
  {
    slug: 'imphal',
    name: 'Imphal',
    state: 'manipur',
    district: 'Imphal West',
    tier: 3,
    localities: [
      'Thangal Bazar',
      'Paona Bazar',
      'Uripok',
      'Sagolband',
      'Keishampat',
      'Kwakeithel',
      'Lamphelpat',
      'Porompat',
      'Khurai',
    ],
    landmarks: ['Kangla Fort', 'Ima Keithel', 'Loktak Lake'],
    climate: 'moderate',
    housing: ['independent', 'mixed'],
    housingNote:
      'Valley homes in Imphal are predominantly independent, with a growing apartment market near Lamphelpat.',
    styleNote:
      'Meitei handloom and Longpi black pottery are distinctive local accents.',
    priceIndex: 1.0,
    nearby: ['guwahati', 'silchar'],
    geo: { lat: 24.817, lng: 93.9368 },
  },
  {
    slug: 'aizawl',
    name: 'Aizawl',
    state: 'mizoram',
    district: 'Aizawl',
    tier: 3,
    localities: [
      'Zarkawt',
      'Dawrpui',
      'Chanmari',
      'Khatla',
      'Bawngkawn',
      'Durtlang',
      'Tuikual',
      'Mission Veng',
      'Zemabawk',
    ],
    climate: 'cold-hill',
    housing: ['independent', 'mixed'],
    housingNote:
      'Steep hillside homes with split levels and tight access dominate Aizawl.',
    styleNote:
      'Puan textiles and flat-pack modular systems suited to hill logistics.',
    priceIndex: 1.05,
    nearby: ['silchar', 'imphal'],
    geo: { lat: 23.7271, lng: 92.7176 },
  },
  {
    slug: 'kohima',
    name: 'Kohima',
    state: 'nagaland',
    district: 'Kohima',
    tier: 3,
    aka: ['Dimapur'],
    localities: [
      'Dimapur',
      'Chümoukedima',
      'Kohima Town',
      'PR Hill',
      'High School Junction',
      'Jotsoma',
      'Meriema',
      'Purana Bazar',
    ],
    landmarks: ['Kohima War Cemetery', 'Kisama Heritage Village'],
    climate: 'cold-hill',
    housing: ['independent', 'mixed'],
    housingNote:
      'Kohima’s hill homes and Dimapur’s plains apartments make up Nagaland’s residential market.',
    styleNote:
      'Naga carved motifs and woven textiles bring strong local character to interiors.',
    priceIndex: 1.02,
    nearby: ['guwahati', 'imphal'],
    geo: { lat: 25.6751, lng: 94.1086 },
  },
  {
    slug: 'itanagar',
    name: 'Itanagar',
    state: 'arunachal-pradesh',
    district: 'Itanagar Capital Complex',
    tier: 3,
    aka: ['Naharlagun'],
    localities: [
      'Naharlagun',
      'Ganga Market',
      'Bank Tinali',
      'Nirjuli',
      'Doimukh',
      'Chimpu',
      'VIP Colony',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'Government and private housing across the Itanagar–Naharlagun capital complex.',
    styleNote: 'Bamboo and cane craft with moisture-resistant modular systems.',
    priceIndex: 1.02,
    nearby: ['guwahati'],
    geo: { lat: 27.0844, lng: 93.6053 },
  },
  {
    slug: 'gangtok',
    name: 'Gangtok',
    state: 'sikkim',
    district: 'Gangtok',
    tier: 3,
    localities: [
      'MG Marg',
      'Tadong',
      'Development Area',
      'Ranipool',
      'Deorali',
      'Tibet Road',
      'Arithang',
      'Sichey',
      'Bojoghari',
    ],
    landmarks: ['MG Marg', 'Rumtek Monastery', 'Tsomgo Lake'],
    climate: 'cold-hill',
    housing: ['independent', 'mixed'],
    housingNote:
      'Gangtok’s brief is dominated by boutique hotels, homestays and hillside family homes stacked along the ridge, most with Kanchenjunga views and tight vehicular access.',
    styleNote:
      'Himalayan-modern — timber, wool, stone and Buddhist-inspired detailing.',
    priceIndex: 1.08,
    nearby: ['siliguri', 'darjeeling'],
    geo: { lat: 27.3389, lng: 88.6065 },
  },
];
