import type { CityData } from '../types';

export const NORTH_CITIES: CityData[] = [
  // ── Delhi ──
  {
    slug: 'new-delhi',
    name: 'Delhi',
    state: 'delhi',
    district: 'New Delhi',
    tier: 1,
    aka: ['New Delhi'],
    localities: [
      'Greater Kailash',
      'Vasant Vihar',
      'Defence Colony',
      'Saket',
      'Dwarka',
      'Rohini',
      'Pitampura',
      'Punjabi Bagh',
      'Mayur Vihar',
      'Vasant Kunj',
      'Hauz Khas',
      'Lajpat Nagar',
      'Janakpuri',
      'Chhatarpur',
      'Shalimar Bagh',
      'Model Town',
      'Civil Lines',
      'Safdarjung Enclave',
    ],
    landmarks: ['India Gate', 'Connaught Place', 'Qutub Minar', 'Lotus Temple'],
    climate: 'composite',
    housing: ['builder-floor', 'high-rise', 'independent', 'heritage'],
    housingNote:
      'Delhi’s residential fabric ranges from South Delhi builder floors and Lutyens bungalows to DDA flats in Dwarka and Rohini and luxury farmhouses in Chhatarpur and Westend Greens.',
    styleNote:
      'Clients are design-savvy and expect confident material choices — Italian marble, fluted panelling, brass inlay — executed with precision.',
    marketNote:
      'Kirti Nagar furniture market and the NCR vendor ecosystem give us the widest sourcing options in the country.',
    priceIndex: 1.15,
    nearby: ['gurugram', 'noida', 'ghaziabad', 'faridabad', 'greater-noida'],
    geo: { lat: 28.6139, lng: 77.209 },
  },
  // ── Haryana ──
  {
    slug: 'gurugram',
    name: 'Gurugram',
    state: 'haryana',
    district: 'Gurugram',
    tier: 1,
    aka: ['Gurgaon'],
    localities: [
      'Golf Course Road',
      'Golf Course Extension Road',
      'Sohna Road',
      'DLF Phase 1–5',
      'Sushant Lok',
      'Sector 56',
      'Sector 57',
      'New Gurugram (Sectors 81–95)',
      'Dwarka Expressway',
      'MG Road',
      'South City',
      'Nirvana Country',
      'Palam Vihar',
      'Sector 42',
      'Sector 43',
    ],
    landmarks: ['Cyber Hub', 'Ambience Mall', 'Kingdom of Dreams'],
    climate: 'composite',
    housing: ['high-rise', 'gated-villa', 'builder-floor'],
    housingNote:
      'Gurugram is India’s luxury condominium capital — DLF Camellias, Magnolias, M3M and Emaar towers along Golf Course Road, plus villa enclaves and builder floors in DLF Phases 1–4.',
    styleNote:
      'Expectations are international: double-height living rooms, home automation, walk-in wardrobes and hotel-grade bathrooms.',
    priceIndex: 1.2,
    nearby: ['new-delhi', 'faridabad', 'noida', 'sohna'],
    geo: { lat: 28.4595, lng: 77.0266 },
  },
  {
    slug: 'faridabad',
    name: 'Faridabad',
    state: 'haryana',
    district: 'Faridabad',
    tier: 2,
    localities: [
      'Sector 14',
      'Sector 15',
      'Sector 16',
      'Sector 21',
      'Greater Faridabad (Neharpar)',
      'Sector 84',
      'Sector 86',
      'NIT Faridabad',
      'Surajkund',
      'Charmwood Village',
      'Ballabhgarh',
    ],
    landmarks: ['Surajkund', 'Badkhal Lake'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'builder-floor'],
    housingNote:
      'Older sectors have large independent plots while Greater Faridabad and the Neharpar belt are full of new group-housing towers.',
    styleNote:
      'Buyers here want Gurugram-level finishes at more grounded budgets — a sweet spot for our transparent pricing.',
    priceIndex: 1.05,
    nearby: ['new-delhi', 'gurugram', 'noida'],
    geo: { lat: 28.4089, lng: 77.3178 },
  },
  {
    slug: 'panchkula',
    name: 'Panchkula',
    state: 'haryana',
    district: 'Panchkula',
    tier: 3,
    localities: [
      'Sector 2',
      'Sector 8',
      'Sector 10',
      'Sector 20',
      'Mansa Devi Complex',
      'Pinjore',
      'Kalka',
      'Zirakpur border',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A planned satellite of Chandigarh with sector housing and new towers toward the Shivalik foothills.',
    styleNote:
      'Chandigarh’s modernist restraint carries over — clean lines, terrazzo and honest wood.',
    priceIndex: 1.02,
    nearby: ['chandigarh-city', 'mohali', 'shimla'],
    geo: { lat: 30.6942, lng: 76.8606 },
  },
  {
    slug: 'karnal',
    name: 'Karnal',
    state: 'haryana',
    district: 'Karnal',
    tier: 3,
    localities: [
      'Sector 6',
      'Sector 7',
      'Sector 13',
      'Model Town',
      'Prem Nagar',
      'Ram Nagar',
      'Kunjpura Road',
    ],
    climate: 'composite',
    housing: ['independent', 'builder-floor'],
    housingNote:
      'A prosperous agri-business city with large kothis on wide plots and a growing builder-floor market.',
    styleNote:
      'Grand, celebratory living rooms and large kitchens are the norm.',
    priceIndex: 0.95,
    nearby: ['panipat', 'chandigarh-city', 'new-delhi'],
    geo: { lat: 29.6857, lng: 76.9905 },
  },
  {
    slug: 'panipat',
    name: 'Panipat',
    state: 'haryana',
    district: 'Panipat',
    tier: 3,
    localities: [
      'Model Town',
      'Sector 11',
      'Sector 12',
      'Sector 25',
      'HUDA',
      'Tehsil Camp',
      'Sanoli Road',
    ],
    climate: 'composite',
    housing: ['independent', 'builder-floor'],
    housingNote:
      'India’s textile city — home to handloom and export houses — has affluent independent homes in Model Town and the HUDA sectors.',
    styleNote:
      'Direct access to Panipat’s rug and upholstery mills lets us customise soft furnishings at source.',
    priceIndex: 0.95,
    nearby: ['karnal', 'new-delhi', 'sonipat'],
    geo: { lat: 29.3909, lng: 76.9635 },
  },
  {
    slug: 'sonipat',
    name: 'Sonipat',
    state: 'haryana',
    district: 'Sonipat',
    tier: 3,
    localities: [
      'Sector 14',
      'Sector 15',
      'Model Town',
      'Kundli',
      'TDI City',
      'Rajiv Gandhi Education City',
      'Murthal',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Kundli and TDI City townships along NH-44 are drawing Delhi families to larger plots and villas.',
    styleNote:
      'Villa-scale interiors with formal and family living zones are common.',
    priceIndex: 0.98,
    nearby: ['new-delhi', 'panipat'],
    geo: { lat: 28.9931, lng: 77.0151 },
  },
  {
    slug: 'hisar',
    name: 'Hisar',
    state: 'haryana',
    district: 'Hisar',
    tier: 3,
    localities: [
      'Urban Estate',
      'Model Town',
      'Sector 13',
      'Sector 15',
      'Azad Nagar',
      'Mill Gate',
      'Rajgarh Road',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'builder-floor'],
    housingNote:
      'A steel and agriculture hub with large independent kothis in Urban Estate and Model Town.',
    styleNote:
      'Heat-conscious design — shaded courtyards, stone floors and light palettes — is important in Hisar’s dry summers.',
    priceIndex: 0.92,
    nearby: ['rohtak', 'new-delhi'],
    geo: { lat: 29.1492, lng: 75.7217 },
  },
  {
    slug: 'rohtak',
    name: 'Rohtak',
    state: 'haryana',
    district: 'Rohtak',
    tier: 3,
    localities: [
      'Sector 1',
      'Sector 3',
      'Model Town',
      'Subhash Nagar',
      'Delhi Road',
      'Prem Nagar',
      'Omaxe City',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'builder-floor', 'gated-villa'],
    housingNote:
      'Rohtak’s sector housing and the Omaxe township cater to a professional and academic population.',
    styleNote:
      'Practical, spacious homes with strong storage and simple elegance are the preferred style.',
    priceIndex: 0.93,
    nearby: ['hisar', 'new-delhi', 'gurugram'],
    geo: { lat: 28.8955, lng: 76.6066 },
  },
  {
    slug: 'sohna',
    name: 'Sohna',
    state: 'haryana',
    district: 'Gurugram',
    tier: 3,
    aka: ['South Gurugram'],
    localities: [
      'Sector 33',
      'Sector 35',
      'Sector 36',
      'Sohna Road',
      'Central Park Flower Valley',
      'Godrej Retreat',
      'Damdama Lake',
    ],
    climate: 'composite',
    housing: ['gated-villa', 'high-rise'],
    housingNote:
      'South Gurugram is a new villa and low-rise township corridor along the Aravalli foothills.',
    styleNote:
      'Resort-style villa interiors with indoor–outdoor flow are the signature brief.',
    priceIndex: 1.1,
    nearby: ['gurugram', 'new-delhi', 'faridabad'],
    geo: { lat: 28.2477, lng: 77.0653 },
  },

  // ── Uttar Pradesh ──
  {
    slug: 'noida',
    name: 'Noida',
    state: 'uttar-pradesh',
    district: 'Gautam Buddha Nagar',
    tier: 1,
    localities: [
      'Sector 15',
      'Sector 44',
      'Sector 50',
      'Sector 62',
      'Sector 75',
      'Sector 76',
      'Sector 78',
      'Sector 93',
      'Sector 100',
      'Sector 128',
      'Sector 137',
      'Sector 150',
      'Noida Expressway',
      'Jaypee Greens Wish Town',
      'ATS Greens',
      'Sector 168',
    ],
    landmarks: [
      'DLF Mall of India',
      'Botanical Garden',
      'Okhla Bird Sanctuary',
    ],
    climate: 'composite',
    housing: ['high-rise', 'independent', 'builder-floor'],
    housingNote:
      'Noida is a high-rise city — Sectors 75–78, 100, 137 and 150 are full of 2BHK/3BHK/4BHK towers, while older sectors (15, 44, 50) have independent plots.',
    styleNote:
      'A young professional population wants smart, modern interiors with strong storage and work-from-home zones.',
    marketNote:
      'We have standardised modular kits for the most common Noida tower floor plates.',
    priceIndex: 1.1,
    nearby: ['greater-noida', 'new-delhi', 'ghaziabad', 'gurugram'],
    geo: { lat: 28.5355, lng: 77.391 },
  },
  {
    slug: 'greater-noida',
    name: 'Greater Noida',
    state: 'uttar-pradesh',
    district: 'Gautam Buddha Nagar',
    tier: 2,
    localities: [
      'Greater Noida West (Noida Extension)',
      'Gaur City',
      'Techzone 4',
      'Sector Alpha',
      'Sector Beta',
      'Sector Gamma',
      'Pari Chowk',
      'Omicron',
      'Zeta',
      'Yamuna Expressway',
      'Jaypee Greens',
      'Ace City',
    ],
    landmarks: ['Buddh International Circuit', 'Pari Chowk', 'India Expo Mart'],
    climate: 'composite',
    housing: ['high-rise', 'gated-villa', 'independent'],
    housingNote:
      'Noida Extension has some of NCR’s highest apartment density, while Alpha–Zeta sectors and the Yamuna Expressway have plots and villas.',
    styleNote:
      'Value-conscious buyers want maximum design impact per rupee — our transparent estimates work well here.',
    priceIndex: 1.02,
    nearby: ['noida', 'new-delhi', 'ghaziabad'],
    geo: { lat: 28.4744, lng: 77.504 },
  },
  {
    slug: 'ghaziabad',
    name: 'Ghaziabad',
    state: 'uttar-pradesh',
    district: 'Ghaziabad',
    tier: 2,
    localities: [
      'Indirapuram',
      'Vaishali',
      'Vasundhara',
      'Raj Nagar Extension',
      'Crossings Republik',
      'Kaushambi',
      'Kavi Nagar',
      'Shastri Nagar',
      'NH-24',
      'Wave City',
      'Mohan Nagar',
    ],
    landmarks: ['Shipra Mall', 'Hindon Airport'],
    climate: 'composite',
    housing: ['high-rise', 'independent'],
    housingNote:
      'Indirapuram, Vaishali and Raj Nagar Extension are dense apartment zones; Kavi Nagar and Shastri Nagar have established independent homes.',
    styleNote:
      'Compact-flat optimisation and family-friendly durability are typical asks.',
    priceIndex: 1.02,
    nearby: ['noida', 'new-delhi', 'meerut'],
    geo: { lat: 28.6692, lng: 77.4538 },
  },
  {
    slug: 'lucknow',
    name: 'Lucknow',
    state: 'uttar-pradesh',
    district: 'Lucknow',
    tier: 1,
    localities: [
      'Gomti Nagar',
      'Gomti Nagar Extension',
      'Hazratganj',
      'Aliganj',
      'Indira Nagar',
      'Mahanagar',
      'Jankipuram',
      'Sushant Golf City',
      'Vibhuti Khand',
      'Ashiyana',
      'Alambagh',
      'Rajajipuram',
      'Vrindavan Yojana',
      'Shaheed Path',
    ],
    landmarks: ['Bara Imambara', 'Hazratganj', 'Ambedkar Park'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'gated-villa', 'heritage'],
    housingNote:
      'Lucknow blends Nawabi-era homes with the planned Gomti Nagar and Sushant Golf City townships along Shaheed Path.',
    styleNote:
      'Awadhi refinement — arches, jaali screens, chikankari-inspired textures and soft pastels — is a distinctive local design language.',
    priceIndex: 0.95,
    nearby: ['kanpur', 'ayodhya', 'prayagraj', 'varanasi'],
    geo: { lat: 26.8467, lng: 80.9462 },
  },
  {
    slug: 'kanpur',
    name: 'Kanpur',
    state: 'uttar-pradesh',
    district: 'Kanpur Nagar',
    tier: 2,
    localities: [
      'Swaroop Nagar',
      'Civil Lines',
      'Kakadeo',
      'Kidwai Nagar',
      'Arya Nagar',
      'Tilak Nagar',
      'Shyam Nagar',
      'Kalyanpur',
      'Barra',
      'Govind Nagar',
      'Mall Road',
      'Ratan Lal Nagar',
    ],
    landmarks: ['IIT Kanpur', 'JK Temple', 'Green Park Stadium'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'mixed'],
    housingNote:
      'An industrial and educational city with large independent homes in Swaroop Nagar and Civil Lines and newer apartments in Kalyanpur and Kakadeo.',
    styleNote:
      'Leather is Kanpur’s signature industry — locally made leather upholstery is a natural accent.',
    priceIndex: 0.92,
    nearby: ['lucknow', 'prayagraj'],
    geo: { lat: 26.4499, lng: 80.3319 },
  },
  {
    slug: 'varanasi',
    name: 'Varanasi',
    state: 'uttar-pradesh',
    district: 'Varanasi',
    tier: 2,
    aka: ['Banaras', 'Kashi'],
    localities: [
      'Sigra',
      'Mahmoorganj',
      'Lanka',
      'Bhelupur',
      'Sarnath',
      'Cantonment',
      'Sunderpur',
      'Nadesar',
      'Durgakund',
      'Ashok Nagar',
      'Pandeypur',
    ],
    landmarks: [
      'Kashi Vishwanath Temple',
      'Dashashwamedh Ghat',
      'Sarnath',
      'BHU',
    ],
    climate: 'composite',
    housing: ['heritage', 'independent', 'high-rise'],
    housingNote:
      'The world’s oldest living city mixes ghat-side heritage homes with new apartments in Sigra, Mahmoorganj and along the Ring Road.',
    styleNote:
      'Banarasi brocade, brass and the spiritual palette of the ghats inspire rich, layered interiors and calm hospitality spaces.',
    priceIndex: 0.93,
    nearby: ['prayagraj', 'lucknow', 'patna'],
    geo: { lat: 25.3176, lng: 82.9739 },
  },
  {
    slug: 'agra',
    name: 'Agra',
    state: 'uttar-pradesh',
    district: 'Agra',
    tier: 2,
    localities: [
      'Kamla Nagar',
      'Dayalbagh',
      'Sikandra',
      'Tajganj',
      'Civil Lines',
      'Sanjay Place',
      'Shahganj',
      'Lohamandi',
      'Awas Vikas',
      'Fatehabad Road',
    ],
    landmarks: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'Agra’s residential growth is along Fatehabad Road, Sikandra and Dayalbagh, with independent homes and mid-rise apartments.',
    styleNote:
      'Mughal pietra dura inlay and jaali work are local crafts we adapt into feature walls and furniture.',
    priceIndex: 0.92,
    nearby: ['mathura', 'new-delhi', 'jaipur'],
    geo: { lat: 27.1767, lng: 78.0081 },
  },
  {
    slug: 'prayagraj',
    name: 'Prayagraj',
    state: 'uttar-pradesh',
    district: 'Prayagraj',
    tier: 2,
    aka: ['Allahabad'],
    localities: [
      'Civil Lines',
      'George Town',
      'Tagore Town',
      'Ashok Nagar',
      'Naini',
      'Jhunsi',
      'Kareli',
      'Mumfordganj',
      'Lukerganj',
    ],
    landmarks: ['Triveni Sangam', 'Anand Bhavan', 'Allahabad High Court'],
    climate: 'composite',
    housing: ['heritage', 'independent', 'high-rise'],
    housingNote:
      'A judicial and academic city with colonial bungalows in Civil Lines and George Town and new apartments toward Naini and Jhunsi.',
    styleNote:
      'Clients favour classic, dignified interiors — libraries, panelled studies and formal living rooms.',
    priceIndex: 0.9,
    nearby: ['varanasi', 'lucknow', 'kanpur'],
    geo: { lat: 25.4358, lng: 81.8463 },
  },
  {
    slug: 'meerut',
    name: 'Meerut',
    state: 'uttar-pradesh',
    district: 'Meerut',
    tier: 2,
    localities: [
      'Shastri Nagar',
      'Saket',
      'Pallavpuram',
      'Ganga Nagar',
      'Modipuram',
      'Jagriti Vihar',
      'Abu Lane',
      'Delhi Road',
      'Garh Road',
    ],
    climate: 'composite',
    housing: ['independent', 'builder-floor', 'high-rise'],
    housingNote:
      'Meerut’s sports-goods and jewellery wealth funds large independent homes; the RRTS corridor is spurring new towers along Delhi Road.',
    styleNote:
      'Bold, opulent living rooms and generous kitchens are the norm here.',
    priceIndex: 0.95,
    nearby: ['ghaziabad', 'new-delhi', 'noida'],
    geo: { lat: 28.9845, lng: 77.7064 },
  },
  {
    slug: 'gorakhpur',
    name: 'Gorakhpur',
    state: 'uttar-pradesh',
    district: 'Gorakhpur',
    tier: 3,
    localities: [
      'Civil Lines',
      'Betiahata',
      'Mohaddipur',
      'Taramandal',
      'Rustampur',
      'Medical College Road',
      'Golghar',
      'Gorakhnath',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'Eastern UP’s hub is expanding fast around Taramandal and Medical College Road with new apartments and independent plots.',
    styleNote:
      'Terracotta craft from nearby Aurangabad village is a distinctive local accent.',
    priceIndex: 0.88,
    nearby: ['lucknow', 'varanasi', 'patna'],
    geo: { lat: 26.7606, lng: 83.3732 },
  },
  {
    slug: 'bareilly',
    name: 'Bareilly',
    state: 'uttar-pradesh',
    district: 'Bareilly',
    tier: 3,
    localities: [
      'Civil Lines',
      'Rajendra Nagar',
      'Pilibhit Bypass',
      'Ramganga Nagar',
      'Green Park',
      'Cantt',
      'Prem Nagar',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A growing city with new housing along the Pilibhit Bypass and Ramganga Nagar, plus established Civil Lines bungalows.',
    styleNote:
      'Zari-zardozi embroidery and cane furniture are Bareilly specialities we use in soft furnishings.',
    priceIndex: 0.88,
    nearby: ['lucknow', 'moradabad', 'new-delhi'],
    geo: { lat: 28.367, lng: 79.4304 },
  },
  {
    slug: 'moradabad',
    name: 'Moradabad',
    state: 'uttar-pradesh',
    district: 'Moradabad',
    tier: 3,
    localities: [
      'Civil Lines',
      'Buddhi Vihar',
      'Ram Ganga Vihar',
      'Kanth Road',
      'Delhi Road',
      'Jigar Colony',
      'Ashiyana',
    ],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The brass city’s export wealth supports a strong independent-home market along Kanth Road and Delhi Road.',
    styleNote:
      'Locally made brass hardware, lighting and décor give Moradabad interiors an authentic signature.',
    priceIndex: 0.88,
    nearby: ['bareilly', 'new-delhi', 'ghaziabad'],
    geo: { lat: 28.8386, lng: 78.7733 },
  },
  {
    slug: 'aligarh',
    name: 'Aligarh',
    state: 'uttar-pradesh',
    district: 'Aligarh',
    tier: 3,
    localities: [
      'Civil Lines',
      'Ramghat Road',
      'Marris Road',
      'Sasni Gate',
      'Agra Road',
      'Dhorra',
      'Medical Road',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'A university city (AMU) with faculty homes and a growing residential belt along Ramghat Road.',
    styleNote:
      'Aligarh’s lock and hardware industry gives us bespoke metal fittings at source.',
    priceIndex: 0.88,
    nearby: ['agra', 'new-delhi', 'mathura'],
    geo: { lat: 27.8974, lng: 78.088 },
  },
  {
    slug: 'mathura',
    name: 'Mathura',
    state: 'uttar-pradesh',
    district: 'Mathura',
    tier: 3,
    aka: ['Vrindavan'],
    localities: [
      'Vrindavan',
      'Krishna Nagar',
      'Civil Lines',
      'Chhatikara Road',
      'Goverdhan Road',
      'Dampier Nagar',
      'Radha Kund',
    ],
    landmarks: ['Krishna Janmabhoomi', 'Banke Bihari Temple', 'Prem Mandir'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'Vrindavan’s spiritual tourism has created a boom in retirement flats, ashram guesthouses and second homes along Chhatikara Road.',
    styleNote:
      'Serene, devotional interiors with sandstone, brass and calm palettes are the essence of our Mathura projects.',
    priceIndex: 0.9,
    nearby: ['agra', 'new-delhi', 'aligarh'],
    geo: { lat: 27.4924, lng: 77.6737 },
  },
  {
    slug: 'ayodhya',
    name: 'Ayodhya',
    state: 'uttar-pradesh',
    district: 'Ayodhya',
    tier: 3,
    aka: ['Faizabad'],
    localities: [
      'Naya Ghat',
      'Ram Path',
      'Civil Lines Faizabad',
      'Deokali',
      'Rikabganj',
      'Bhakti Path',
      'Airport Road',
    ],
    landmarks: ['Ram Mandir', 'Hanuman Garhi', 'Saryu Ghat'],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'Ayodhya is India’s newest hospitality hotspot — hotels, dharamshalas and homestays are being built at record pace alongside new residential colonies.',
    styleNote:
      'Temple-town warmth — sandstone, teak and devotional motifs — defines the local aesthetic.',
    priceIndex: 0.92,
    nearby: ['lucknow', 'gorakhpur'],
    geo: { lat: 26.7922, lng: 82.1998 },
  },
  {
    slug: 'jhansi',
    name: 'Jhansi',
    state: 'uttar-pradesh',
    district: 'Jhansi',
    tier: 3,
    localities: [
      'Civil Lines',
      'Nandanpura',
      'Sipri Bazar',
      'Gwalior Road',
      'Kanpur Road',
      'Bundelkhand University Area',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'Bundelkhand’s main city has large independent homes and a developing apartment market along Gwalior Road.',
    styleNote:
      'Stone floors, thick walls and shaded interiors suit the region’s dry heat.',
    priceIndex: 0.86,
    nearby: ['gwalior', 'kanpur'],
    geo: { lat: 25.4484, lng: 78.5685 },
  },

  // ── Punjab ──
  {
    slug: 'chandigarh-city',
    name: 'Chandigarh',
    state: 'chandigarh',
    district: 'Chandigarh',
    tier: 2,
    localities: [
      'Sector 8',
      'Sector 9',
      'Sector 10',
      'Sector 11',
      'Sector 15',
      'Sector 17',
      'Sector 21',
      'Sector 33',
      'Sector 35',
      'Sector 44',
      'Manimajra',
      'IT Park',
    ],
    landmarks: ['Rock Garden', 'Sukhna Lake', 'Capitol Complex'],
    climate: 'composite',
    housing: ['independent', 'row-house', 'high-rise'],
    housingNote:
      'Corbusier’s planned sectors have fixed façades and plot sizes; the interior is where families personalise their homes.',
    styleNote:
      'Modernist honesty — exposed brick, terrazzo, concrete and warm wood — is a natural fit here.',
    priceIndex: 1.05,
    nearby: ['mohali', 'panchkula', 'zirakpur', 'ludhiana'],
    geo: { lat: 30.7333, lng: 76.7794 },
  },
  {
    slug: 'mohali',
    name: 'Mohali',
    state: 'punjab',
    district: 'Sahibzada Ajit Singh Nagar (Mohali)',
    tier: 2,
    aka: ['SAS Nagar'],
    localities: [
      'Sector 70',
      'Sector 71',
      'Phase 3B2',
      'Phase 7',
      'Phase 11',
      'Sector 91',
      'Aerocity',
      'Kharar',
      'Mullanpur (New Chandigarh)',
      'Airport Road',
      'Sector 115',
    ],
    landmarks: ['PCA Stadium', 'Chandigarh International Airport'],
    climate: 'composite',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Mohali’s Airport Road, Aerocity and New Chandigarh corridors are among Punjab’s fastest-growing luxury markets.',
    styleNote:
      'Buyers want Chandigarh’s clean lines with more warmth and bolder statement pieces.',
    priceIndex: 1.02,
    nearby: ['chandigarh-city', 'zirakpur', 'panchkula'],
    geo: { lat: 30.7046, lng: 76.7179 },
  },
  {
    slug: 'zirakpur',
    name: 'Zirakpur',
    state: 'punjab',
    district: 'Sahibzada Ajit Singh Nagar (Mohali)',
    tier: 3,
    localities: [
      'VIP Road',
      'Patiala Road',
      'Peer Muchalla',
      'Dhakoli',
      'Ambala Highway',
      'Gazipur',
      'Baltana',
    ],
    climate: 'composite',
    housing: ['high-rise', 'independent'],
    housingNote:
      'A high-rise satellite of Chandigarh with dense apartment towers along VIP Road and the Ambala highway.',
    styleNote:
      'Efficient 2BHK/3BHK interiors with maximum storage are the dominant brief.',
    priceIndex: 0.98,
    nearby: ['chandigarh-city', 'mohali', 'panchkula'],
    geo: { lat: 30.6425, lng: 76.8173 },
  },
  {
    slug: 'ludhiana',
    name: 'Ludhiana',
    state: 'punjab',
    district: 'Ludhiana',
    tier: 2,
    localities: [
      'Sarabha Nagar',
      'Model Town',
      'BRS Nagar',
      'Civil Lines',
      'Pakhowal Road',
      'Dugri',
      'South City',
      'Ferozepur Road',
      'Kitchlu Nagar',
      'Gurdev Nagar',
      'Omaxe Royal Residency',
    ],
    landmarks: ['Punjab Agricultural University', 'Nehru Rose Garden'],
    climate: 'composite',
    housing: ['independent', 'gated-villa', 'high-rise'],
    housingNote:
      'Punjab’s industrial capital has grand kothis in Sarabha Nagar and Model Town and new gated townships along Ferozepur Road and Pakhowal Road.',
    styleNote:
      'Luxury is expressed generously — marble foyers, chandeliers, panelled ceilings and large formal dining rooms.',
    priceIndex: 1.0,
    nearby: ['chandigarh-city', 'jalandhar', 'patiala'],
    geo: { lat: 30.901, lng: 75.8573 },
  },
  {
    slug: 'jalandhar',
    name: 'Jalandhar',
    state: 'punjab',
    district: 'Jalandhar',
    tier: 2,
    localities: [
      'Model Town',
      'Urban Estate',
      'Guru Gobind Singh Avenue',
      'Mota Singh Nagar',
      'Adarsh Nagar',
      'Lajpat Nagar',
      'Nakodar Road',
      'Cantonment',
      'Jalandhar Heights',
    ],
    climate: 'composite',
    housing: ['independent', 'gated-villa'],
    housingNote:
      'The NRI capital of Punjab — many homes are built for families abroad and managed remotely.',
    styleNote:
      'Our remote-approval workflow (3D + weekly video reports) was refined on Jalandhar NRI projects.',
    priceIndex: 0.98,
    nearby: ['ludhiana', 'amritsar', 'chandigarh-city'],
    geo: { lat: 31.326, lng: 75.5762 },
  },
  {
    slug: 'amritsar',
    name: 'Amritsar',
    state: 'punjab',
    district: 'Amritsar',
    tier: 2,
    localities: [
      'Ranjit Avenue',
      'Green Avenue',
      'Lawrence Road',
      'Majitha Road',
      'Basant Avenue',
      'White Avenue',
      'Mall Road',
      'GT Road',
      'Batala Road',
      'Model Town',
    ],
    landmarks: ['Golden Temple', 'Jallianwala Bagh', 'Wagah Border'],
    climate: 'composite',
    housing: ['independent', 'heritage', 'high-rise'],
    housingNote:
      'Ranjit Avenue and Green Avenue have large kothis; the walled city has heritage havelis being restored as homes and boutique hotels.',
    styleNote:
      'Phulkari embroidery, Sikh heritage motifs and warm brass accents give Amritsar interiors a distinct identity.',
    priceIndex: 0.98,
    nearby: ['jalandhar', 'ludhiana'],
    geo: { lat: 31.634, lng: 74.8723 },
  },
  {
    slug: 'patiala',
    name: 'Patiala',
    state: 'punjab',
    district: 'Patiala',
    tier: 3,
    localities: [
      'Urban Estate',
      'Model Town',
      'Leela Bhawan',
      'Tripuri',
      'Sirhind Road',
      'Rajpura Road',
      'Bhupindra Nagar',
    ],
    landmarks: ['Qila Mubarak', 'Sheesh Mahal'],
    climate: 'composite',
    housing: ['independent', 'heritage'],
    housingNote:
      'A royal city with heritage homes and modern kothis in Urban Estate and Model Town.',
    styleNote:
      'Patiala’s regal legacy inspires ornate detailing balanced with contemporary comfort.',
    priceIndex: 0.95,
    nearby: ['chandigarh-city', 'ludhiana'],
    geo: { lat: 30.3398, lng: 76.3869 },
  },
  {
    slug: 'bathinda',
    name: 'Bathinda',
    state: 'punjab',
    district: 'Bathinda',
    tier: 3,
    localities: [
      'Model Town',
      'Civil Lines',
      'Guru Nanak Nagar',
      'Green Avenue',
      'Goniana Road',
      'Bhagu Road',
      'Ganesha Basti',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'builder-floor'],
    housingNote:
      'Malwa’s commercial hub is expanding with independent homes and new apartments along Goniana Road.',
    styleNote:
      'Dry, hot summers call for shaded design and heat-stable finishes.',
    priceIndex: 0.92,
    nearby: ['ludhiana', 'patiala'],
    geo: { lat: 30.211, lng: 74.9455 },
  },

  // ── Himachal Pradesh ──
  {
    slug: 'shimla',
    name: 'Shimla',
    state: 'himachal-pradesh',
    district: 'Shimla',
    tier: 3,
    localities: [
      'The Mall',
      'Chhota Shimla',
      'Sanjauli',
      'Kasumpti',
      'New Shimla',
      'Summer Hill',
      'Panthaghati',
      'Mehli',
      'Kufri',
    ],
    landmarks: ['The Ridge', 'Jakhoo Temple', 'Viceregal Lodge'],
    climate: 'cold-hill',
    housing: ['heritage', 'independent', 'mixed'],
    housingNote:
      'Shimla’s colonial cottages and modern flats in New Shimla and Panthaghati both need insulated, compact and view-oriented interiors.',
    styleNote:
      'Timber panelling, wool textiles and warm lighting create cosy hill-station interiors.',
    priceIndex: 1.08,
    nearby: ['chandigarh-city', 'panchkula', 'solan'],
    geo: { lat: 31.1048, lng: 77.1734 },
  },
  {
    slug: 'dharamshala',
    name: 'Dharamshala',
    state: 'himachal-pradesh',
    district: 'Kangra',
    tier: 3,
    aka: ['McLeod Ganj'],
    localities: [
      'McLeod Ganj',
      'Dharamkot',
      'Bhagsu',
      'Sidhbari',
      'Kotwali Bazar',
      'Naddi',
      'Palampur',
    ],
    landmarks: ['Tsuglagkhang Complex', 'HPCA Stadium'],
    climate: 'cold-hill',
    housing: ['independent', 'mixed'],
    housingNote:
      'Homestays, cafés and mountain homes dominate — many owned by expats and remote workers.',
    styleNote:
      'Tibetan-influenced colour, slate and deodar make for distinctive, grounded interiors.',
    priceIndex: 1.05,
    nearby: ['shimla', 'chandigarh-city'],
    geo: { lat: 32.219, lng: 76.3234 },
  },
  {
    slug: 'solan',
    name: 'Solan',
    state: 'himachal-pradesh',
    district: 'Solan',
    tier: 3,
    aka: ['Kasauli', 'Parwanoo', 'Baddi'],
    localities: [
      'Kasauli',
      'Parwanoo',
      'Baddi',
      'Barog',
      'Dharampur',
      'Chambaghat',
      'Kandaghat',
    ],
    climate: 'cold-hill',
    housing: ['independent', 'gated-villa'],
    housingNote:
      'The Solan–Kasauli belt is Chandigarh’s weekend-home country, with the Baddi industrial zone adding professional housing demand.',
    styleNote:
      'Rustic-modern cottages with stone, pine and big glass frontages are the signature style.',
    priceIndex: 1.02,
    nearby: ['shimla', 'chandigarh-city', 'panchkula'],
    geo: { lat: 30.9045, lng: 77.0967 },
  },

  // ── Uttarakhand ──
  {
    slug: 'dehradun',
    name: 'Dehradun',
    state: 'uttarakhand',
    district: 'Dehradun',
    tier: 2,
    localities: [
      'Rajpur Road',
      'Vasant Vihar',
      'Sahastradhara Road',
      'GMS Road',
      'Race Course',
      'Dalanwala',
      'Ballupur',
      'Prem Nagar',
      'Clement Town',
      'Mussoorie Road',
      'Jakhan',
      'Kaulagarh',
    ],
    landmarks: ['Forest Research Institute', 'Robber’s Cave', 'Doon School'],
    climate: 'moderate',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'A retirement and education city with leafy bungalows in Dalanwala and Vasant Vihar and new apartments along Sahastradhara Road.',
    styleNote:
      'Calm, nature-led interiors — wood, stone, indoor greenery — reflect the Doon valley setting.',
    priceIndex: 1.0,
    nearby: ['haridwar', 'rishikesh', 'mussoorie', 'new-delhi'],
    geo: { lat: 30.3165, lng: 78.0322 },
  },
  {
    slug: 'haridwar',
    name: 'Haridwar',
    state: 'uttarakhand',
    district: 'Haridwar',
    tier: 3,
    localities: [
      'Kankhal',
      'Jwalapur',
      'BHEL Township',
      'Shivalik Nagar',
      'Bahadrabad',
      'SIDCUL',
      'Har Ki Pauri area',
      'Roorkee',
    ],
    landmarks: ['Har Ki Pauri', 'Mansa Devi Temple'],
    climate: 'moderate',
    housing: ['independent', 'row-house', 'mixed'],
    housingNote:
      'BHEL and SIDCUL industrial townships plus a strong ashram and guesthouse market.',
    styleNote:
      'Wellness-inspired, low-VOC interiors with natural lime and wood are a frequent brief.',
    priceIndex: 0.95,
    nearby: ['dehradun', 'rishikesh'],
    geo: { lat: 29.9457, lng: 78.1642 },
  },
  {
    slug: 'rishikesh',
    name: 'Rishikesh',
    state: 'uttarakhand',
    district: 'Dehradun',
    tier: 3,
    localities: [
      'Tapovan',
      'Laxman Jhula',
      'Ram Jhula',
      'Swarg Ashram',
      'Shyampur',
      'Muni Ki Reti',
      'Jonk',
    ],
    landmarks: ['Laxman Jhula', 'Triveni Ghat', 'Beatles Ashram'],
    climate: 'moderate',
    housing: ['independent', 'mixed'],
    housingNote:
      'The yoga capital’s demand is for retreats, boutique stays and wellness homes in Tapovan and along the Ganga.',
    styleNote:
      'Earthy, minimal, meditative interiors with river views are what clients come for.',
    priceIndex: 1.0,
    nearby: ['haridwar', 'dehradun'],
    geo: { lat: 30.0869, lng: 78.2676 },
  },
  {
    slug: 'mussoorie',
    name: 'Mussoorie',
    state: 'uttarakhand',
    district: 'Dehradun',
    tier: 3,
    localities: [
      'Mall Road',
      'Landour',
      'Library Bazaar',
      'Barlowganj',
      'Kempty',
      'Happy Valley',
    ],
    landmarks: ['Kempty Falls', 'Lal Tibba', 'Landour'],
    climate: 'cold-hill',
    housing: ['heritage', 'independent'],
    housingNote:
      'Colonial cottages and boutique hotels in Landour and along the Mall need conservation-sensitive, insulated interiors.',
    styleNote:
      'Heritage hill-station charm — fireplaces, panelled walls, bay windows — is the design signature.',
    priceIndex: 1.1,
    nearby: ['dehradun', 'rishikesh'],
    geo: { lat: 30.4598, lng: 78.0644 },
  },
  {
    slug: 'haldwani',
    name: 'Haldwani',
    state: 'uttarakhand',
    district: 'Nainital',
    tier: 3,
    aka: ['Nainital'],
    localities: [
      'Kathgodam',
      'Mukhani',
      'Kusumkhera',
      'Rampur Road',
      'Nainital Road',
      'Bareilly Road',
      'Nainital',
      'Bhimtal',
    ],
    climate: 'moderate',
    housing: ['independent', 'mixed'],
    housingNote:
      'The gateway to Kumaon and its lake district; homes range from Haldwani apartments to lake-view cottages in Nainital and Bhimtal.',
    styleNote:
      'Kumaoni aipan motifs and pine-wood detailing give interiors a regional identity.',
    priceIndex: 0.98,
    nearby: ['dehradun', 'bareilly'],
    geo: { lat: 29.2183, lng: 79.5133 },
  },

  // ── Jammu & Kashmir / Ladakh ──
  {
    slug: 'jammu',
    name: 'Jammu',
    state: 'jammu-and-kashmir',
    district: 'Jammu',
    tier: 2,
    localities: [
      'Gandhi Nagar',
      'Trikuta Nagar',
      'Channi Himmat',
      'Talab Tillo',
      'Bakshi Nagar',
      'Sainik Colony',
      'Greater Kailash',
      'Sidhra',
      'Nanak Nagar',
      'Bari Brahmana',
    ],
    landmarks: ['Bahu Fort', 'Raghunath Temple', 'Vaishno Devi (Katra)'],
    climate: 'composite',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The winter capital has spacious independent homes in Gandhi Nagar and Trikuta Nagar and a growing apartment market toward Sidhra.',
    styleNote:
      'Dogra heritage — carved walnut, Basohli-inspired colour — meets modern practicality.',
    priceIndex: 0.98,
    nearby: ['srinagar', 'chandigarh-city', 'amritsar'],
    geo: { lat: 32.7266, lng: 74.857 },
  },
  {
    slug: 'srinagar',
    name: 'Srinagar',
    state: 'jammu-and-kashmir',
    district: 'Srinagar',
    tier: 2,
    localities: [
      'Rajbagh',
      'Jawahar Nagar',
      'Hyderpora',
      'Bemina',
      'Lal Chowk',
      'Nishat',
      'Sanat Nagar',
      'Barzulla',
      'Gogji Bagh',
      'Dal Gate',
    ],
    landmarks: ['Dal Lake', 'Mughal Gardens', 'Hazratbal'],
    climate: 'cold-hill',
    housing: ['independent', 'heritage', 'mixed'],
    housingNote:
      'Srinagar homes are typically large, multi-storey independent houses; hotels and houseboats add a significant hospitality market.',
    styleNote:
      'Khatamband ceilings, pinjrakari lattice, walnut carving and hand-knotted carpets are living local crafts we build around.',
    priceIndex: 1.05,
    nearby: ['jammu'],
    geo: { lat: 34.0837, lng: 74.7973 },
  },
  {
    slug: 'leh',
    name: 'Leh',
    state: 'ladakh',
    district: 'Leh',
    tier: 3,
    localities: [
      'Changspa',
      'Skara',
      'Sankar',
      'Choglamsar',
      'Shey',
      'Upper Tukcha',
      'Housing Colony',
    ],
    landmarks: ['Leh Palace', 'Shanti Stupa', 'Thiksey Monastery'],
    climate: 'cold-hill',
    housing: ['independent', 'mixed'],
    housingNote:
      'Guesthouses, hotels and homes built for a short summer season and long, brutal winters.',
    styleNote:
      'Rammed earth, timber ceilings, low seating and passive-solar planning define Ladakhi-modern interiors.',
    priceIndex: 1.18,
    nearby: ['srinagar'],
    geo: { lat: 34.1526, lng: 77.5771 },
  },
];
