import type { CityData } from '../types';

export const SOUTH_CITIES: CityData[] = [
  // ── Karnataka ──
  {
    slug: 'bengaluru',
    name: 'Bengaluru',
    state: 'karnataka',
    district: 'Bengaluru Urban',
    tier: 1,
    aka: ['Bangalore'],
    localities: [
      'Whitefield',
      'Sarjapur Road',
      'Koramangala',
      'Indiranagar',
      'HSR Layout',
      'Electronic City',
      'Hebbal',
      'Yelahanka',
      'JP Nagar',
      'Jayanagar',
      'Bannerghatta Road',
      'Marathahalli',
      'Bellandur',
      'Kanakapura Road',
      'Rajarajeshwari Nagar',
      'Malleshwaram',
      'Basavanagudi',
      'Thanisandra',
      'Devanahalli',
      'Hennur',
      'KR Puram',
      'Varthur',
      'Banashankari',
      'Kengeri',
    ],
    landmarks: ['Cubbon Park', 'Lalbagh', 'Vidhana Soudha', 'UB City'],
    climate: 'moderate',
    housing: ['high-rise', 'gated-villa', 'independent', 'builder-floor'],
    housingNote:
      'Bengaluru’s tech corridors (Whitefield, Sarjapur, Electronic City, Hebbal) are dense with apartment communities, while Jayanagar, Malleshwaram and Indiranagar retain independent homes and villa communities line Kanakapura and Sarjapur Roads.',
    styleNote:
      'A young, global clientele wants Scandinavian-clean, plant-filled, tech-integrated homes with dedicated work-from-home zones.',
    marketNote:
      'Bengaluru’s mild climate is the most material-forgiving of any Indian metro — natural veneers and open shelving age beautifully.',
    priceIndex: 1.1,
    nearby: ['mysuru', 'hosur', 'chennai', 'hubballi'],
    geo: { lat: 12.9716, lng: 77.5946 },
  },
  {
    slug: 'mysuru',
    name: 'Mysuru',
    state: 'karnataka',
    district: 'Mysuru',
    tier: 2,
    aka: ['Mysore'],
    localities: [
      'Vijayanagar',
      'Jayalakshmipuram',
      'Kuvempunagar',
      'Gokulam',
      'Saraswathipuram',
      'Hebbal Industrial Area',
      'Bogadi',
      'Hootagalli',
      'Nazarbad',
      'Yadavagiri',
      'Bannimantap',
      'Lakshmipuram',
    ],
    landmarks: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens'],
    climate: 'moderate',
    housing: ['independent', 'high-rise', 'heritage'],
    housingNote:
      'A heritage city with wide plotted layouts (Vijayanagar, Kuvempunagar) and a new IT-driven apartment market near Hebbal and Hootagalli.',
    styleNote:
      'Mysore rosewood inlay, sandalwood and silk are living local crafts we bring into feature pieces.',
    priceIndex: 0.95,
    nearby: ['bengaluru', 'mangaluru', 'coimbatore'],
    geo: { lat: 12.2958, lng: 76.6394 },
  },
  {
    slug: 'mangaluru',
    name: 'Mangaluru',
    state: 'karnataka',
    district: 'Dakshina Kannada',
    tier: 2,
    aka: ['Mangalore'],
    localities: [
      'Kadri',
      'Bejai',
      'Kankanady',
      'Falnir',
      'Lalbagh',
      'Derebail',
      'Surathkal',
      'Kulur',
      'Bondel',
      'Kottara',
      'Ullal',
      'Pumpwell',
    ],
    landmarks: [
      'Panambur Beach',
      'Kadri Manjunath Temple',
      'St. Aloysius Chapel',
    ],
    climate: 'tropical-wet',
    housing: ['high-rise', 'independent'],
    housingNote:
      'A coastal port and education city with a strong NRI/Gulf-funded home market and high-rise growth in Kadri and Bejai.',
    styleNote:
      'Mangalore tiles, red laterite and Konkan-coast teak give interiors an honest tropical character.',
    priceIndex: 1.0,
    nearby: ['udupi', 'mysuru', 'bengaluru', 'panaji'],
    geo: { lat: 12.9141, lng: 74.856 },
  },
  {
    slug: 'udupi',
    name: 'Udupi',
    state: 'karnataka',
    district: 'Udupi',
    tier: 3,
    aka: ['Manipal'],
    localities: [
      'Manipal',
      'Kunjibettu',
      'Malpe',
      'Santhekatte',
      'Ambagilu',
      'Kadiyali',
      'Brahmavar',
    ],
    landmarks: ['Sri Krishna Matha', 'Malpe Beach', 'Manipal University'],
    climate: 'tropical-wet',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A temple and university town with strong student housing demand in Manipal and family homes across Udupi.',
    styleNote:
      'Traditional Tulu-Nadu homes with sloping tiled roofs inspire wood-and-terracotta interiors.',
    priceIndex: 0.97,
    nearby: ['mangaluru'],
    geo: { lat: 13.3409, lng: 74.7421 },
  },
  {
    slug: 'hubballi',
    name: 'Hubballi–Dharwad',
    state: 'karnataka',
    district: 'Dharwad',
    tier: 2,
    aka: ['Hubli', 'Dharwad'],
    localities: [
      'Vidyanagar',
      'Gokul Road',
      'Keshwapur',
      'Deshpande Nagar',
      'Unkal',
      'Navanagar',
      'Dharwad Saptapur',
      'Kalyan Nagar',
      'Tarihal',
    ],
    climate: 'moderate',
    housing: ['independent', 'high-rise'],
    housingNote:
      'North Karnataka’s twin-city hub is growing along Gokul Road and Navanagar with apartments and independent plots.',
    styleNote:
      'Practical, family-first interiors with generous storage are the norm.',
    priceIndex: 0.9,
    nearby: ['belagavi', 'bengaluru', 'panaji'],
    geo: { lat: 15.3647, lng: 75.124 },
  },
  {
    slug: 'belagavi',
    name: 'Belagavi',
    state: 'karnataka',
    district: 'Belagavi',
    tier: 3,
    aka: ['Belgaum'],
    localities: [
      'Tilakwadi',
      'Camp',
      'Shahapur',
      'Hindwadi',
      'Vadgaon',
      'Sadashiv Nagar',
      'Angol',
      'Hanuman Nagar',
    ],
    climate: 'moderate',
    housing: ['independent', 'mixed'],
    housingNote:
      'A pleasant-climate city near Goa with cantonment-era bungalows and new apartments in Tilakwadi and Hindwadi.',
    styleNote: 'Mild weather allows an open, wood-rich material palette.',
    priceIndex: 0.9,
    nearby: ['hubballi', 'panaji', 'kolhapur'],
    geo: { lat: 15.8497, lng: 74.4977 },
  },

  // ── Tamil Nadu ──
  {
    slug: 'chennai',
    name: 'Chennai',
    state: 'tamil-nadu',
    district: 'Chennai',
    tier: 1,
    aka: ['Madras'],
    localities: [
      'Adyar',
      'Anna Nagar',
      'T. Nagar',
      'Velachery',
      'OMR (Old Mahabalipuram Road)',
      'ECR',
      'Porur',
      'Nungambakkam',
      'Besant Nagar',
      'Mylapore',
      'Sholinganallur',
      'Perungudi',
      'Thoraipakkam',
      'Medavakkam',
      'Tambaram',
      'Pallikaranai',
      'Kilpauk',
      'Alwarpet',
      'Mogappair',
      'Ambattur',
      'Perumbakkam',
      'Guindy',
    ],
    landmarks: ['Marina Beach', 'Kapaleeshwarar Temple', 'Fort St. George'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'independent', 'gated-villa'],
    housingNote:
      'Chennai’s OMR and ECR corridors are lined with IT-driven apartment communities; Adyar, Anna Nagar and Alwarpet hold independent homes and premium flats.',
    styleNote:
      'Vastu compliance, a dedicated pooja room and heat-conscious planning are almost always part of the brief; Chettinad and Athangudi elements add authentic character.',
    marketNote:
      'Coastal humidity makes BWP boards, ventilated wardrobes and rust-proof hardware standard in every Chennai project.',
    priceIndex: 1.05,
    nearby: ['coimbatore', 'bengaluru', 'pondicherry', 'vellore'],
    geo: { lat: 13.0827, lng: 80.2707 },
  },
  {
    slug: 'coimbatore',
    name: 'Coimbatore',
    state: 'tamil-nadu',
    district: 'Coimbatore',
    tier: 1,
    aka: ['Kovai'],
    localities: [
      'RS Puram',
      'Saibaba Colony',
      'Peelamedu',
      'Saravanampatti',
      'Vadavalli',
      'Race Course',
      'Singanallur',
      'Ganapathy',
      'Kalapatti',
      'Thudiyalur',
      'Ramanathapuram',
      'Avinashi Road',
      'Trichy Road',
      'Kovaipudur',
      'Sulur',
    ],
    landmarks: ['Marudamalai Temple', 'Isha Yoga Center', 'Brookefields Mall'],
    climate: 'moderate',
    housing: ['independent', 'gated-villa', 'high-rise'],
    housingNote:
      'The Manchester of South India has a pleasant climate, a strong industrial-family bungalow tradition in RS Puram and Race Course, and IT-led apartments in Saravanampatti.',
    styleNote:
      'Coimbatore’s manufacturing base means custom metalwork, motors and modular hardware are all made locally.',
    priceIndex: 0.97,
    nearby: ['tiruppur', 'erode', 'chennai', 'kochi'],
    geo: { lat: 11.0168, lng: 76.9558 },
  },
  {
    slug: 'madurai',
    name: 'Madurai',
    state: 'tamil-nadu',
    district: 'Madurai',
    tier: 2,
    localities: [
      'KK Nagar',
      'Anna Nagar',
      'Bypass Road',
      'Villapuram',
      'Thirunagar',
      'Ellis Nagar',
      'Chokkikulam',
      'SS Colony',
      'Tallakulam',
      'Vilangudi',
      'Mattuthavani',
    ],
    landmarks: ['Meenakshi Amman Temple', 'Thirumalai Nayakkar Mahal'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The temple city has a proud independent-house culture and growing apartments along the Bypass Road and KK Nagar.',
    styleNote:
      'Traditional Tamil homes with a central mutram (courtyard), Athangudi tiles and carved pillars inspire our layouts here.',
    priceIndex: 0.9,
    nearby: ['tiruchirappalli', 'coimbatore', 'tirunelveli'],
    geo: { lat: 9.9252, lng: 78.1198 },
  },
  {
    slug: 'tiruchirappalli',
    name: 'Tiruchirappalli',
    state: 'tamil-nadu',
    district: 'Tiruchirappalli',
    tier: 2,
    aka: ['Trichy'],
    localities: [
      'Thillai Nagar',
      'KK Nagar',
      'Srirangam',
      'Cantonment',
      'Woraiyur',
      'Crawford',
      'Karumandapam',
      'Puthur',
      'Ariyamangalam',
      'Thiruverumbur',
    ],
    landmarks: ['Rockfort Temple', 'Srirangam Temple', 'NIT Trichy'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A central Tamil Nadu hub with BHEL, NIT and a strong independent-home market in Thillai Nagar and KK Nagar.',
    styleNote:
      'Heat management — cross ventilation, stone floors, light palettes — is central to design in Trichy.',
    priceIndex: 0.9,
    nearby: ['madurai', 'thanjavur', 'coimbatore'],
    geo: { lat: 10.7905, lng: 78.7047 },
  },
  {
    slug: 'salem',
    name: 'Salem',
    state: 'tamil-nadu',
    district: 'Salem',
    tier: 3,
    localities: [
      'Fairlands',
      'Hasthampatti',
      'Alagapuram',
      'Ammapet',
      'Seelanaickenpatti',
      'Kondalampatti',
      'Suramangalam',
      'Yercaud',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'A steel and textile city with independent homes in Fairlands and hill retreats in nearby Yercaud.',
    styleNote:
      'Salem’s silver and steel industries provide locally made hardware and accents.',
    priceIndex: 0.88,
    nearby: ['coimbatore', 'erode', 'bengaluru'],
    geo: { lat: 11.6643, lng: 78.146 },
  },
  {
    slug: 'tiruppur',
    name: 'Tiruppur',
    state: 'tamil-nadu',
    district: 'Tiruppur',
    tier: 3,
    localities: [
      'Avinashi Road',
      'Palladam Road',
      'Kumaran Road',
      'Perumanallur',
      'Pushpa Nagar',
      'Anupparpalayam',
      'Dharapuram Road',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'gated-villa'],
    housingNote:
      'India’s knitwear capital has a wealthy exporter class building large bungalows along Avinashi and Palladam Roads.',
    styleNote:
      'Direct access to cotton textiles lets us customise upholstery, drapery and bedding at source.',
    priceIndex: 0.92,
    nearby: ['coimbatore', 'erode'],
    geo: { lat: 11.1085, lng: 77.3411 },
  },
  {
    slug: 'erode',
    name: 'Erode',
    state: 'tamil-nadu',
    district: 'Erode',
    tier: 3,
    localities: [
      'Perundurai Road',
      'Sathy Road',
      'Veerappanchatram',
      'Surampatti',
      'Thindal',
      'Kollampalayam',
      'Chithode',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'A turmeric and textile trading city with spacious independent homes and new plots along Perundurai Road.',
    styleNote:
      'Traditional Kongu-region homes inspire courtyard-centred, well-ventilated layouts.',
    priceIndex: 0.88,
    nearby: ['coimbatore', 'tiruppur', 'salem'],
    geo: { lat: 11.341, lng: 77.7172 },
  },
  {
    slug: 'vellore',
    name: 'Vellore',
    state: 'tamil-nadu',
    district: 'Vellore',
    tier: 3,
    localities: [
      'Katpadi',
      'Gandhi Nagar',
      'Sathuvachari',
      'Bagayam',
      'Thorapadi',
      'Ranipet',
      'Arcot',
    ],
    landmarks: ['Vellore Fort', 'CMC Hospital', 'VIT University'],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'A medical and education hub with strong rental and family-home demand around CMC and VIT.',
    styleNote:
      'Practical, easy-maintenance interiors for medical professionals and academics.',
    priceIndex: 0.88,
    nearby: ['chennai', 'bengaluru'],
    geo: { lat: 12.9165, lng: 79.1325 },
  },
  {
    slug: 'thanjavur',
    name: 'Thanjavur',
    state: 'tamil-nadu',
    district: 'Thanjavur',
    tier: 3,
    aka: ['Tanjore', 'Kumbakonam'],
    localities: [
      'Medical College Road',
      'Arulananda Nagar',
      'Nanjikottai Road',
      'Karanthai',
      'Kumbakonam',
      'Vallam',
    ],
    landmarks: ['Brihadeeswarar Temple', 'Saraswathi Mahal Library'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage'],
    housingNote:
      'The Chola heartland has heritage agraharam homes and modern independent houses.',
    styleNote:
      'Tanjore paintings, bronze work and Chettinad-influenced woodwork are authentic local elements.',
    priceIndex: 0.86,
    nearby: ['tiruchirappalli', 'madurai'],
    geo: { lat: 10.787, lng: 79.1378 },
  },
  {
    slug: 'tirunelveli',
    name: 'Tirunelveli',
    state: 'tamil-nadu',
    district: 'Tirunelveli',
    tier: 3,
    aka: ['Nellai'],
    localities: [
      'Palayamkottai',
      'Maharaja Nagar',
      'KTC Nagar',
      'Town',
      'Vannarpettai',
      'Perumalpuram',
      'Thoothukudi',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'South Tamil Nadu’s hub, with independent homes in Palayamkottai and Maharaja Nagar and port-city demand in nearby Thoothukudi.',
    styleNote:
      'Courtyard homes with granite and teak reflect the region’s traditional building culture.',
    priceIndex: 0.86,
    nearby: ['madurai', 'thiruvananthapuram'],
    geo: { lat: 8.7139, lng: 77.7567 },
  },
  {
    slug: 'hosur',
    name: 'Hosur',
    state: 'tamil-nadu',
    district: 'Krishnagiri',
    tier: 3,
    localities: [
      'SIPCOT',
      'Bagalur Road',
      'Mathigiri',
      'Zuzuvadi',
      'Rayakottai Road',
      'Denkanikottai Road',
      'Attibele border',
    ],
    climate: 'moderate',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'An industrial satellite of Bengaluru with rapidly growing apartment and villa projects on Bagalur Road.',
    styleNote:
      'Bengaluru-style contemporary interiors at more accessible prices.',
    priceIndex: 0.95,
    nearby: ['bengaluru', 'salem'],
    geo: { lat: 12.7409, lng: 77.8253 },
  },
  {
    slug: 'pondicherry',
    name: 'Puducherry',
    state: 'puducherry',
    district: 'Puducherry',
    tier: 3,
    aka: ['Pondicherry'],
    localities: [
      'White Town',
      'Tamil Quarter',
      'Lawspet',
      'Muthialpet',
      'Reddiarpalayam',
      'Auroville',
      'ECR Pondicherry',
      'Villianur',
      'Ariyankuppam',
      'Kottakuppam',
    ],
    landmarks: ['Promenade Beach', 'Aurobindo Ashram', 'Auroville'],
    climate: 'humid-coastal',
    housing: ['heritage', 'independent', 'high-rise'],
    housingNote:
      'French-colonial villas in White Town, Franco-Tamil houses in the Tamil Quarter and new apartments in Lawspet and along ECR.',
    styleNote:
      'Mustard and ochre walls, tall louvred windows, lime plaster and courtyards define Pondicherry’s unmistakable look.',
    priceIndex: 0.98,
    nearby: ['chennai', 'cuddalore'],
    geo: { lat: 11.9416, lng: 79.8083 },
  },
  {
    slug: 'cuddalore',
    name: 'Cuddalore',
    state: 'tamil-nadu',
    district: 'Cuddalore',
    tier: 3,
    aka: ['Chidambaram'],
    localities: [
      'Manjakuppam',
      'Thirupapuliyur',
      'Semmandalam',
      'Vandipalayam',
      'Chidambaram',
      'Panruti',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'A coastal district town with independent homes and temple-town demand in Chidambaram.',
    styleNote:
      'Salt-resistant, breathable finishes are essential this close to the sea.',
    priceIndex: 0.86,
    nearby: ['pondicherry', 'chennai'],
    geo: { lat: 11.748, lng: 79.7714 },
  },

  // ── Telangana ──
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'telangana',
    district: 'Hyderabad',
    tier: 1,
    localities: [
      'Gachibowli',
      'Kokapet',
      'Jubilee Hills',
      'Banjara Hills',
      'Madhapur',
      'HITEC City',
      'Kondapur',
      'Manikonda',
      'Narsingi',
      'Tellapur',
      'Nanakramguda',
      'Financial District',
      'Miyapur',
      'Kukatpally',
      'Bachupally',
      'Kompally',
      'Uppal',
      'LB Nagar',
      'Attapur',
      'Secunderabad',
      'Begumpet',
      'Himayatnagar',
      'Shamshabad',
      'Puppalaguda',
    ],
    landmarks: ['Charminar', 'Golconda Fort', 'HITEC City'],
    climate: 'composite',
    housing: ['high-rise', 'gated-villa', 'independent'],
    housingNote:
      'Hyderabad’s western corridor (Gachibowli, Kokapet, Narsingi, Tellapur) has India’s largest new apartment towers and sky villas; Jubilee and Banjara Hills hold luxury independent homes.',
    styleNote:
      'Clients expect smart-home automation, home theatres and multi-zone living as standard; Nirmal art, Pochampally ikat and Bidriware add local identity.',
    marketNote:
      '3,000–5,000 sq ft apartments are common here — our multi-zone planning and staff-area design get full use.',
    priceIndex: 1.05,
    nearby: ['warangal', 'vijayawada', 'bengaluru', 'nagpur'],
    geo: { lat: 17.385, lng: 78.4867 },
  },
  {
    slug: 'warangal',
    name: 'Warangal',
    state: 'telangana',
    district: 'Warangal',
    tier: 3,
    aka: ['Hanamkonda', 'Kazipet'],
    localities: [
      'Hanamkonda',
      'Kazipet',
      'Subedari',
      'Naimnagar',
      'Hunter Road',
      'Balasamudram',
      'Nakkalagutta',
      'Kishanpura',
    ],
    landmarks: ['Warangal Fort', 'Thousand Pillar Temple', 'NIT Warangal'],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'The tri-city of Warangal–Hanamkonda–Kazipet has strong independent-home demand and new apartments along Hunter Road.',
    styleNote:
      'Kakatiya-era stone motifs and Pembarthi brass craft are proudly local.',
    priceIndex: 0.9,
    nearby: ['hyderabad', 'karimnagar'],
    geo: { lat: 17.9689, lng: 79.5941 },
  },
  {
    slug: 'karimnagar',
    name: 'Karimnagar',
    state: 'telangana',
    district: 'Karimnagar',
    tier: 3,
    localities: [
      'Mukarampura',
      'Kothirampur',
      'Christian Colony',
      'Vavilalapally',
      'Bhagath Nagar',
      'Hyderabad Road',
      'Sircilla Road',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'A growing district city with independent homes and new gated layouts along Hyderabad Road.',
    styleNote:
      'Silver filigree from Karimnagar is a fine local craft for accents.',
    priceIndex: 0.88,
    nearby: ['warangal', 'hyderabad'],
    geo: { lat: 18.4386, lng: 79.1288 },
  },
  {
    slug: 'nizamabad',
    name: 'Nizamabad',
    state: 'telangana',
    district: 'Nizamabad',
    tier: 3,
    localities: [
      'Vinayak Nagar',
      'Kanteshwar',
      'Dwaraka Nagar',
      'Subhash Nagar',
      'Armoor Road',
      'Bodhan Road',
      'Khaleelwadi',
    ],
    climate: 'composite',
    housing: ['independent', 'mixed'],
    housingNote:
      'A north Telangana hub with NRI-funded independent homes and new apartments.',
    styleNote:
      'Warm, spacious family homes with pooja rooms and large kitchens.',
    priceIndex: 0.88,
    nearby: ['hyderabad', 'karimnagar'],
    geo: { lat: 18.6725, lng: 78.0941 },
  },

  // ── Andhra Pradesh ──
  {
    slug: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'andhra-pradesh',
    district: 'Visakhapatnam',
    tier: 1,
    aka: ['Vizag'],
    localities: [
      'MVP Colony',
      'Beach Road',
      'Rushikonda',
      'Madhurawada',
      'Seethammadhara',
      'Dwaraka Nagar',
      'Gajuwaka',
      'Yendada',
      'Kommadi',
      'PM Palem',
      'Lawsons Bay',
      'Siripuram',
      'Kurmannapalem',
      'Bheemunipatnam',
    ],
    landmarks: ['RK Beach', 'Kailasagiri', 'Rushikonda Beach'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'independent', 'gated-villa'],
    housingNote:
      'A sea-facing city with luxury apartments on Beach Road and Rushikonda and IT-led growth in Madhurawada and Kommadi.',
    styleNote:
      'Ocean views drive the design — light, airy palettes, sea-facing balconies and salt-proof materials throughout.',
    priceIndex: 0.98,
    nearby: ['vijayawada', 'bhubaneswar', 'kakinada'],
    geo: { lat: 17.6868, lng: 83.2185 },
  },
  {
    slug: 'vijayawada',
    name: 'Vijayawada',
    state: 'andhra-pradesh',
    district: 'NTR',
    tier: 2,
    aka: ['Amaravati', 'Bezawada'],
    localities: [
      'Benz Circle',
      'MG Road',
      'Labbipet',
      'Moghalrajpuram',
      'Gurunanak Colony',
      'Patamata',
      'Poranki',
      'Kanuru',
      'Tadepalli',
      'Mangalagiri',
      'Gollapudi',
      'Bhavanipuram',
      'Amaravati',
    ],
    landmarks: ['Kanaka Durga Temple', 'Prakasam Barrage', 'Undavalli Caves'],
    climate: 'hot-dry',
    housing: ['high-rise', 'independent', 'gated-villa'],
    housingNote:
      'The commercial capital of AP and gateway to Amaravati has premium towers along MG Road and the Tadepalli–Mangalagiri corridor.',
    styleNote:
      'Kondapalli toys, Kalamkari and Mangalagiri cotton are cherished local accents.',
    priceIndex: 0.95,
    nearby: ['guntur', 'hyderabad', 'visakhapatnam'],
    geo: { lat: 16.5062, lng: 80.648 },
  },
  {
    slug: 'guntur',
    name: 'Guntur',
    state: 'andhra-pradesh',
    district: 'Guntur',
    tier: 3,
    localities: [
      'Brodipet',
      'Arundelpet',
      'Lakshmipuram',
      'Pattabhipuram',
      'Gorantla',
      'Nallapadu',
      'Amaravati Road',
      'Chuttugunta',
      'Mangalagiri',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'A wealthy agri-trading city with large independent homes and new apartments on Amaravati Road.',
    styleNote:
      'Spacious multi-hall layouts with formal and family living areas are typical.',
    priceIndex: 0.92,
    nearby: ['vijayawada', 'hyderabad'],
    geo: { lat: 16.3067, lng: 80.4365 },
  },
  {
    slug: 'tirupati',
    name: 'Tirupati',
    state: 'andhra-pradesh',
    district: 'Tirupati',
    tier: 3,
    localities: [
      'Tiruchanoor Road',
      'Renigunta Road',
      'Air Bypass Road',
      'Padmavathipuram',
      'Korlagunta',
      'MR Palli',
      'Alipiri',
      'Sri Kalahasti',
    ],
    landmarks: ['Tirumala Venkateswara Temple', 'Sri Kalahasti'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'Pilgrimage tourism drives hotel and guesthouse interiors alongside a growing family-home market.',
    styleNote:
      'Devotional, calm palettes with granite, teak and brass suit Tirupati’s spiritual character.',
    priceIndex: 0.92,
    nearby: ['chennai', 'bengaluru', 'vellore'],
    geo: { lat: 13.6288, lng: 79.4192 },
  },
  {
    slug: 'kakinada',
    name: 'Kakinada',
    state: 'andhra-pradesh',
    district: 'Kakinada',
    tier: 3,
    aka: ['Rajahmundry'],
    localities: [
      'Sarpavaram',
      'Ramanayyapeta',
      'Bhanugudi',
      'Jagannaickpur',
      'Rajahmundry',
      'Gandhinagar',
      'Surya Rao Peta',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The Godavari delta’s twin cities have affluent independent homes and coastal-industry professional housing.',
    styleNote:
      'Corrosion-resistant hardware and ventilated storage are essential in this humid coastal belt.',
    priceIndex: 0.9,
    nearby: ['visakhapatnam', 'vijayawada'],
    geo: { lat: 16.9891, lng: 82.2475 },
  },
  {
    slug: 'nellore',
    name: 'Nellore',
    state: 'andhra-pradesh',
    district: 'Sri Potti Sriramulu Nellore',
    tier: 3,
    localities: [
      'Magunta Layout',
      'Dargamitta',
      'Vedayapalem',
      'Balaji Nagar',
      'Ramalingapuram',
      'Kanuparthipadu',
      'Podalakur Road',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'An aquaculture and trading city on the Chennai–Vizag highway with large independent homes.',
    styleNote:
      'Heat and humidity demand breathable, light interiors with strong ventilation.',
    priceIndex: 0.9,
    nearby: ['chennai', 'tirupati'],
    geo: { lat: 14.4426, lng: 79.9865 },
  },

  // ── Kerala ──
  {
    slug: 'kochi',
    name: 'Kochi',
    state: 'kerala',
    district: 'Ernakulam',
    tier: 1,
    aka: ['Cochin', 'Ernakulam'],
    localities: [
      'Kakkanad',
      'Edappally',
      'Panampilly Nagar',
      'Marine Drive',
      'Fort Kochi',
      'Vyttila',
      'Kadavanthra',
      'Palarivattom',
      'Tripunithura',
      'Aluva',
      'Kalamassery',
      'Thevara',
      'Vazhakkala',
      'Infopark',
      'Kundannoor',
      'Thrikkakara',
    ],
    landmarks: ['Fort Kochi', 'Marine Drive', 'Lulu Mall', 'Infopark'],
    climate: 'tropical-wet',
    housing: ['high-rise', 'independent', 'gated-villa', 'heritage'],
    housingNote:
      'Kerala’s commercial capital has waterfront luxury towers on Marine Drive, IT-driven apartments in Kakkanad and Dutch-Portuguese heritage homes in Fort Kochi.',
    styleNote:
      'Tropical-modern — nalukettu-inspired courtyards, rosewood and teak, Athangudi floors and cross-ventilation — is our Kochi signature.',
    marketNote:
      'With 3,000+ mm of annual rain, moisture control is the first decision in every Kerala specification.',
    priceIndex: 1.05,
    nearby: ['thrissur', 'kottayam', 'alappuzha', 'thiruvananthapuram'],
    geo: { lat: 9.9312, lng: 76.2673 },
  },
  {
    slug: 'thiruvananthapuram',
    name: 'Thiruvananthapuram',
    state: 'kerala',
    district: 'Thiruvananthapuram',
    tier: 2,
    aka: ['Trivandrum'],
    localities: [
      'Kowdiar',
      'Pattom',
      'Vazhuthacaud',
      'Kazhakkoottam',
      'Technopark',
      'Sasthamangalam',
      'Kesavadasapuram',
      'Peroorkada',
      'Vellayambalam',
      'Kovalam',
      'Sreekaryam',
      'Vattiyoorkavu',
    ],
    landmarks: ['Padmanabhaswamy Temple', 'Kovalam Beach', 'Technopark'],
    climate: 'tropical-wet',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'The state capital has stately homes in Kowdiar and Sasthamangalam and Technopark-driven apartments in Kazhakkoottam.',
    styleNote:
      'Travancore heritage — sloping tiled roofs, wooden ceilings, laterite — informs refined, calm interiors.',
    priceIndex: 1.0,
    nearby: ['kollam', 'kochi', 'tirunelveli'],
    geo: { lat: 8.5241, lng: 76.9366 },
  },
  {
    slug: 'kozhikode',
    name: 'Kozhikode',
    state: 'kerala',
    district: 'Kozhikode',
    tier: 2,
    aka: ['Calicut'],
    localities: [
      'Mavoor Road',
      'Nadakkavu',
      'Chevayur',
      'Eranhipalam',
      'Thondayad',
      'Malaparamba',
      'Vellayil',
      'Kottooli',
      'Pantheerankavu',
      'Cyberpark',
      'Ramanattukara',
    ],
    landmarks: ['Kozhikode Beach', 'Mananchira', 'Kappad'],
    climate: 'tropical-wet',
    housing: ['independent', 'high-rise'],
    housingNote:
      'Malabar’s capital has a strong Gulf-remittance home-building culture with large independent houses and new towers on Mavoor Road.',
    styleNote:
      'Malabar teak, brass lamps and Mappila-influenced detailing make Kozhikode interiors distinctive.',
    priceIndex: 0.98,
    nearby: ['thrissur', 'kannur', 'malappuram', 'kochi'],
    geo: { lat: 11.2588, lng: 75.7804 },
  },
  {
    slug: 'thrissur',
    name: 'Thrissur',
    state: 'kerala',
    district: 'Thrissur',
    tier: 2,
    localities: [
      'Punkunnam',
      'Poothole',
      'Ayyanthole',
      'Kuriachira',
      'Ollur',
      'Mannuthy',
      'Koorkenchery',
      'Viyyur',
      'Chembukkavu',
      'Guruvayur',
      'Kunnamkulam',
    ],
    landmarks: ['Vadakkunnathan Temple', 'Thrissur Pooram', 'Guruvayur Temple'],
    climate: 'tropical-wet',
    housing: ['independent', 'gated-villa', 'high-rise'],
    housingNote:
      'Kerala’s cultural capital and gold hub has affluent independent homes and villa projects around Punkunnam, Ayyanthole and Mannuthy.',
    styleNote:
      'Classic Kerala craftsmanship — carved wood, brass and traditional proportions — is expected and celebrated here.',
    priceIndex: 0.98,
    nearby: ['kochi', 'kozhikode', 'palakkad'],
    geo: { lat: 10.5276, lng: 76.2144 },
  },
  {
    slug: 'kottayam',
    name: 'Kottayam',
    state: 'kerala',
    district: 'Kottayam',
    tier: 3,
    localities: [
      'Kanjikuzhy',
      'Kumaranalloor',
      'Nagampadam',
      'Thirunakkara',
      'Ettumanoor',
      'Pala',
      'Changanassery',
      'Kumarakom',
    ],
    landmarks: ['Kumarakom Backwaters', 'Thirunakkara Temple'],
    climate: 'tropical-wet',
    housing: ['independent', 'gated-villa'],
    housingNote:
      'A rubber-and-education district with NRI-funded villas and backwater resort demand in Kumarakom.',
    styleNote:
      'Backwater-facing, breezy interiors with rosewood and cane define the Kottayam look.',
    priceIndex: 0.97,
    nearby: ['kochi', 'alappuzha'],
    geo: { lat: 9.5916, lng: 76.5222 },
  },
  {
    slug: 'alappuzha',
    name: 'Alappuzha',
    state: 'kerala',
    district: 'Alappuzha',
    tier: 3,
    aka: ['Alleppey'],
    localities: [
      'Thondankulangara',
      'Kalarcode',
      'Punnamada',
      'Cherthala',
      'Ambalapuzha',
      'Haripad',
      'Kayamkulam',
    ],
    landmarks: ['Alappuzha Backwaters', 'Punnamada Lake'],
    climate: 'tropical-wet',
    housing: ['independent', 'heritage'],
    housingNote:
      'Houseboats, homestays and heritage homes dominate the design brief in the Venice of the East.',
    styleNote:
      'Coir, coconut wood and marine-grade systems are locally appropriate and beautiful.',
    priceIndex: 0.97,
    nearby: ['kochi', 'kottayam', 'kollam'],
    geo: { lat: 9.4981, lng: 76.3388 },
  },
  {
    slug: 'kollam',
    name: 'Kollam',
    state: 'kerala',
    district: 'Kollam',
    tier: 3,
    aka: ['Quilon'],
    localities: [
      'Chinnakada',
      'Kadappakada',
      'Asramam',
      'Kilikollur',
      'Kottiyam',
      'Karunagappally',
      'Chavara',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'mixed'],
    housingNote:
      'A cashew-trade port city with large independent homes and lake-facing plots on Ashtamudi.',
    styleNote:
      'Lake views and monsoon-proof material palettes shape our Kollam work.',
    priceIndex: 0.95,
    nearby: ['thiruvananthapuram', 'alappuzha'],
    geo: { lat: 8.8932, lng: 76.6141 },
  },
  {
    slug: 'kannur',
    name: 'Kannur',
    state: 'kerala',
    district: 'Kannur',
    tier: 3,
    localities: [
      'Thavakkara',
      'Thalassery',
      'Payyambalam',
      'Chala',
      'Kakkad',
      'Mattannur',
      'Taliparamba',
    ],
    landmarks: ['St. Angelo Fort', 'Payyambalam Beach', 'Kannur Airport'],
    climate: 'tropical-wet',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The new airport has boosted Kannur’s NRI-home and hospitality market.',
    styleNote:
      'Kannur handloom textiles are a celebrated local resource for soft furnishings.',
    priceIndex: 0.95,
    nearby: ['kozhikode', 'mangaluru'],
    geo: { lat: 11.8745, lng: 75.3704 },
  },
  {
    slug: 'malappuram',
    name: 'Malappuram',
    state: 'kerala',
    district: 'Malappuram',
    tier: 3,
    aka: ['Manjeri', 'Tirur'],
    localities: [
      'Up Hill',
      'Down Hill',
      'Manjeri',
      'Tirur',
      'Perinthalmanna',
      'Kottakkal',
      'Ponnani',
      'Nilambur',
    ],
    climate: 'tropical-wet',
    housing: ['independent', 'gated-villa'],
    housingNote:
      'Kerala’s most populous district builds some of its largest Gulf-funded homes.',
    styleNote:
      'Grand, multi-generational villas with elaborate woodwork are the norm.',
    priceIndex: 0.96,
    nearby: ['kozhikode', 'thrissur'],
    geo: { lat: 11.051, lng: 76.0711 },
  },
  {
    slug: 'palakkad',
    name: 'Palakkad',
    state: 'kerala',
    district: 'Palakkad',
    tier: 3,
    localities: [
      'Sultanpet',
      'Olavakkode',
      'Kalmandapam',
      'Chandranagar',
      'Kanjikode',
      'Ottapalam',
      'Shoranur',
    ],
    climate: 'moderate',
    housing: ['independent', 'heritage'],
    housingNote:
      'The gateway to Kerala from Coimbatore, with agraharam heritage streets and new plotted layouts.',
    styleNote:
      'Drier than the coast, Palakkad allows a broader material palette while retaining Kerala warmth.',
    priceIndex: 0.93,
    nearby: ['coimbatore', 'thrissur'],
    geo: { lat: 10.7867, lng: 76.6548 },
  },
];
