import type { CityData } from '../types';

export const WEST_CITIES: CityData[] = [
  // ── Maharashtra ──
  {
    slug: 'mumbai',
    name: 'Mumbai',
    state: 'maharashtra',
    district: 'Mumbai Suburban',
    tier: 1,
    aka: ['Bombay'],
    localities: [
      'Bandra',
      'Juhu',
      'Andheri',
      'Powai',
      'Worli',
      'Lower Parel',
      'Malabar Hill',
      'Colaba',
      'Chembur',
      'Ghatkopar',
      'Mulund',
      'Goregaon',
      'Kandivali',
      'Borivali',
      'Dadar',
      'Parel',
      'Santacruz',
      'Khar',
      'Versova',
      'Wadala',
      'Sion',
      'Bhandup',
    ],
    landmarks: ['Gateway of India', 'Marine Drive', 'Bandra–Worli Sea Link'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'heritage', 'mixed'],
    housingNote:
      'Mumbai apartments are compact and expensive per square foot — 1BHK/2BHK in the suburbs, luxury towers in Worli, Lower Parel and Bandra, and redeveloped buildings across the city.',
    styleNote:
      'Space intelligence is everything: multifunctional furniture, ceiling-height storage, sliding partitions and light palettes that make 700 sq ft feel generous.',
    marketNote:
      'Sea air demands marine-grade boards and SS-304 hardware in every coastal ward from Colaba to Borivali.',
    priceIndex: 1.2,
    nearby: ['navi-mumbai', 'thane', 'pune', 'kalyan'],
    geo: { lat: 19.076, lng: 72.8777 },
  },
  {
    slug: 'navi-mumbai',
    name: 'Navi Mumbai',
    state: 'maharashtra',
    district: 'Thane',
    tier: 1,
    localities: [
      'Vashi',
      'Nerul',
      'Kharghar',
      'Panvel',
      'Belapur',
      'Seawoods',
      'Airoli',
      'Sanpada',
      'Ulwe',
      'Taloja',
      'Kamothe',
      'Ghansoli',
      'Koparkhairane',
    ],
    landmarks: [
      'Seawoods Grand Central',
      'Kharghar Hills',
      'Navi Mumbai International Airport',
    ],
    climate: 'humid-coastal',
    housing: ['high-rise', 'gated-villa'],
    housingNote:
      'A CIDCO-planned city with node-based apartment complexes; Kharghar, Ulwe and Panvel are booming with the new airport.',
    styleNote:
      'Buyers get more space than Mumbai and want it to feel premium — full-home turnkey projects are the norm.',
    priceIndex: 1.1,
    nearby: ['mumbai', 'thane', 'pune'],
    geo: { lat: 19.033, lng: 73.0297 },
  },
  {
    slug: 'thane',
    name: 'Thane',
    state: 'maharashtra',
    district: 'Thane',
    tier: 1,
    localities: [
      'Ghodbunder Road',
      'Hiranandani Estate',
      'Majiwada',
      'Kolshet',
      'Manpada',
      'Pokhran Road',
      'Vartak Nagar',
      'Naupada',
      'Kasarvadavali',
      'Balkum',
      'Dombivli',
      'Kalyan',
    ],
    landmarks: ['Upvan Lake', 'Viviana Mall', 'Yeoor Hills'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'mixed'],
    housingNote:
      'Ghodbunder Road and Pokhran Road host large township projects (Hiranandani, Lodha, Rustomjee) with standard 2BHK/3BHK plans.',
    styleNote:
      'Families upgrading from Mumbai want brighter, larger-feeling homes with strong storage and kid-friendly durability.',
    priceIndex: 1.1,
    nearby: ['mumbai', 'navi-mumbai', 'kalyan'],
    geo: { lat: 19.2183, lng: 72.9781 },
  },
  {
    slug: 'kalyan',
    name: 'Kalyan–Dombivli',
    state: 'maharashtra',
    district: 'Thane',
    tier: 2,
    aka: ['Kalyan', 'Dombivli'],
    localities: [
      'Kalyan West',
      'Kalyan East',
      'Dombivli East',
      'Dombivli West',
      'Khadakpada',
      'Palava City',
      'Shil Phata',
      'Ambernath',
      'Badlapur',
      'Ulhasnagar',
    ],
    climate: 'humid-coastal',
    housing: ['high-rise', 'mixed'],
    housingNote:
      'The Palava township and dense Dombivli housing make this one of MMR’s biggest affordable-to-mid segment markets.',
    styleNote:
      'Smart, budget-optimised 1BHK/2BHK interiors with full-height storage are the core brief.',
    priceIndex: 1.0,
    nearby: ['thane', 'mumbai', 'navi-mumbai'],
    geo: { lat: 19.2403, lng: 73.1305 },
  },
  {
    slug: 'pune',
    name: 'Pune',
    state: 'maharashtra',
    district: 'Pune',
    tier: 1,
    localities: [
      'Koregaon Park',
      'Kalyani Nagar',
      'Baner',
      'Aundh',
      'Wakad',
      'Hinjewadi',
      'Kharadi',
      'Viman Nagar',
      'Hadapsar',
      'Magarpatta',
      'Kothrud',
      'Bavdhan',
      'Balewadi',
      'Pimple Saudagar',
      'Undri',
      'NIBM Road',
      'Wagholi',
      'Ravet',
      'Pimpri-Chinchwad',
      'Deccan',
      'Camp',
    ],
    landmarks: ['Shaniwar Wada', 'Aga Khan Palace', 'Phoenix Marketcity'],
    climate: 'moderate',
    housing: ['high-rise', 'gated-villa', 'independent', 'row-house'],
    housingNote:
      'Pune’s IT corridors (Hinjewadi, Kharadi, Magarpatta) have thousands of similar 2BHK/3BHK plans, while Koregaon Park, Kalyani Nagar and Baner host premium apartments and row houses.',
    styleNote:
      'A cosmopolitan, well-travelled clientele favours warm-minimal interiors with natural wood, greenery and work-from-home nooks.',
    marketNote:
      'Pune’s pleasant climate makes it one of the most material-forgiving cities we work in.',
    priceIndex: 1.08,
    nearby: ['mumbai', 'navi-mumbai', 'nashik', 'kolhapur'],
    geo: { lat: 18.5204, lng: 73.8567 },
  },
  {
    slug: 'nagpur',
    name: 'Nagpur',
    state: 'maharashtra',
    district: 'Nagpur',
    tier: 2,
    localities: [
      'Dharampeth',
      'Civil Lines',
      'Ramdaspeth',
      'Wardha Road',
      'Manish Nagar',
      'Besa',
      'Pratap Nagar',
      'Sadar',
      'Khamla',
      'Hingna',
      'Koradi Road',
      'MIHAN',
      'Bhandara Road',
    ],
    landmarks: ['Deekshabhoomi', 'Futala Lake', 'Zero Mile'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'The orange city has a strong independent-bungalow culture in Dharampeth and Ramdaspeth, with new towers along Wardha Road and MIHAN.',
    styleNote:
      'Summer heat above 45°C drives our material choices — heat-stable finishes, stone floors and deep shading.',
    priceIndex: 0.95,
    nearby: ['raipur', 'bhopal', 'pune'],
    geo: { lat: 21.1458, lng: 79.0882 },
  },
  {
    slug: 'nashik',
    name: 'Nashik',
    state: 'maharashtra',
    district: 'Nashik',
    tier: 2,
    localities: [
      'Gangapur Road',
      'College Road',
      'Indira Nagar',
      'Pathardi Phata',
      'Deolali',
      'Nashik Road',
      'Mahatma Nagar',
      'Satpur',
      'Cidco',
      'Panchavati',
      'Ashoka Marg',
    ],
    landmarks: ['Trimbakeshwar', 'Sula Vineyards', 'Panchavati'],
    climate: 'moderate',
    housing: ['independent', 'high-rise', 'row-house'],
    housingNote:
      'India’s wine capital has a growing professional population and pleasant weather; Gangapur Road and Pathardi Phata lead the new-home market.',
    styleNote:
      'Vineyard-inspired, relaxed interiors with natural textures suit the city’s lifestyle.',
    priceIndex: 0.95,
    nearby: ['pune', 'mumbai', 'aurangabad'],
    geo: { lat: 19.9975, lng: 73.7898 },
  },
  {
    slug: 'aurangabad',
    name: 'Chhatrapati Sambhajinagar',
    state: 'maharashtra',
    district: 'Chhatrapati Sambhajinagar (Aurangabad)',
    tier: 2,
    aka: ['Aurangabad'],
    localities: [
      'CIDCO',
      'Jalna Road',
      'Beed Bypass',
      'Garkheda',
      'Ulkanagari',
      'Kanchanwadi',
      'Waluj',
      'Samarth Nagar',
      'Nirala Bazar',
    ],
    landmarks: ['Bibi Ka Maqbara', 'Ajanta Caves', 'Ellora Caves'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise'],
    housingNote:
      'An industrial city (Waluj, Shendra) with growing residential belts along Jalna Road and the Beed Bypass.',
    styleNote:
      'Himroo and Paithani weaves are local textiles we bring into soft furnishings.',
    priceIndex: 0.92,
    nearby: ['nashik', 'pune'],
    geo: { lat: 19.8762, lng: 75.3433 },
  },
  {
    slug: 'kolhapur',
    name: 'Kolhapur',
    state: 'maharashtra',
    district: 'Kolhapur',
    tier: 3,
    localities: [
      'Rajarampuri',
      'Tarabai Park',
      'Shahupuri',
      'Nagala Park',
      'Kalamba',
      'Ruikar Colony',
      'Mahadwar Road',
    ],
    landmarks: ['Mahalaxmi Temple', 'New Palace', 'Rankala Lake'],
    climate: 'moderate',
    housing: ['independent', 'mixed'],
    housingNote:
      'A prosperous sugar and foundry city with grand bungalows in Tarabai Park and Rajarampuri.',
    styleNote:
      'Kolhapuri leather and Maratha heritage motifs give interiors a proud local flavour.',
    priceIndex: 0.92,
    nearby: ['pune', 'panaji', 'belagavi'],
    geo: { lat: 16.705, lng: 74.2433 },
  },
  {
    slug: 'solapur',
    name: 'Solapur',
    state: 'maharashtra',
    district: 'Solapur',
    tier: 3,
    localities: [
      'Hotgi Road',
      'Vijapur Road',
      'Jule Solapur',
      'Saat Rasta',
      'Railway Lines',
      'Ashok Chowk',
      'Majarewadi',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'A textile city with mostly independent homes and emerging apartments along Hotgi and Vijapur Roads.',
    styleNote:
      'Solapuri chaddars and cotton textiles are a natural local accent.',
    priceIndex: 0.88,
    nearby: ['pune', 'hyderabad'],
    geo: { lat: 17.6599, lng: 75.9064 },
  },

  // ── Gujarat ──
  {
    slug: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'gujarat',
    district: 'Ahmedabad',
    tier: 1,
    localities: [
      'SG Highway',
      'Satellite',
      'Prahlad Nagar',
      'Bodakdev',
      'Vastrapur',
      'Thaltej',
      'Bopal',
      'South Bopal',
      'Shela',
      'Gota',
      'Chandkheda',
      'Maninagar',
      'Navrangpura',
      'Paldi',
      'Ambli',
      'Science City Road',
      'Shilaj',
      'Naranpura',
    ],
    landmarks: ['Sabarmati Ashram', 'Sabarmati Riverfront', 'Adalaj Stepwell'],
    climate: 'hot-dry',
    housing: ['high-rise', 'gated-villa', 'independent', 'heritage'],
    housingNote:
      'Western Ahmedabad (SG Highway, Bopal, Shela, Thaltej) has India’s most active bungalow-scheme and luxury apartment market; the old city has pol houses with carved wooden façades.',
    styleNote:
      'Gujarati homes are built for gathering — big living-dining spaces, a hinchko swing, dedicated pooja rooms and kitchens designed for elaborate vegetarian cooking.',
    marketNote:
      'Proximity to Morbi’s tile factories and Ahmedabad’s furniture clusters keeps material costs sharp.',
    priceIndex: 1.0,
    nearby: ['gandhinagar', 'vadodara', 'surat', 'rajkot'],
    geo: { lat: 23.0225, lng: 72.5714 },
  },
  {
    slug: 'gandhinagar',
    name: 'Gandhinagar',
    state: 'gujarat',
    district: 'Gandhinagar',
    tier: 2,
    localities: [
      'Sector 1–30',
      'GIFT City',
      'Kudasan',
      'Sargasan',
      'Raysan',
      'Randesan',
      'Koba',
      'Infocity',
      'Pethapur',
      'Adalaj',
    ],
    landmarks: ['GIFT City', 'Akshardham', 'Mahatma Mandir'],
    climate: 'hot-dry',
    housing: ['high-rise', 'gated-villa', 'row-house'],
    housingNote:
      'A planned capital with sector housing and a booming GIFT City–Kudasan–Raysan corridor of premium towers and villas.',
    styleNote:
      'Clean, orderly interiors with generous greenery echo the city’s planned character.',
    priceIndex: 1.0,
    nearby: ['ahmedabad', 'vadodara'],
    geo: { lat: 23.2156, lng: 72.6369 },
  },
  {
    slug: 'surat',
    name: 'Surat',
    state: 'gujarat',
    district: 'Surat',
    tier: 1,
    localities: [
      'Vesu',
      'Pal',
      'Adajan',
      'Piplod',
      'Athwa',
      'City Light',
      'Althan',
      'Dumas Road',
      'Varachha',
      'Katargam',
      'Ghod Dod Road',
      'Bhatar',
      'Palanpur',
      'Jahangirpura',
    ],
    landmarks: ['Surat Diamond Bourse', 'Dumas Beach', 'Dutch Garden'],
    climate: 'humid-coastal',
    housing: ['high-rise', 'gated-villa', 'independent'],
    housingNote:
      'Diamond and textile wealth funds a strong luxury bungalow and high-rise market in Vesu, Pal, Piplod and along Dumas Road.',
    styleNote:
      'Surat clients embrace luxury — double-height living rooms, home theatres, Italian marble and statement lighting.',
    priceIndex: 1.02,
    nearby: ['vadodara', 'ahmedabad', 'mumbai', 'navsari'],
    geo: { lat: 21.1702, lng: 72.8311 },
  },
  {
    slug: 'vadodara',
    name: 'Vadodara',
    state: 'gujarat',
    district: 'Vadodara',
    tier: 2,
    aka: ['Baroda'],
    localities: [
      'Alkapuri',
      'Akota',
      'Vasna Road',
      'Gotri',
      'Bhayli',
      'Manjalpur',
      'Fatehgunj',
      'Sama',
      'Waghodia Road',
      'New VIP Road',
      'Old Padra Road',
      'Karelibaug',
      'Tandalja',
    ],
    landmarks: ['Laxmi Vilas Palace', 'Sayaji Baug', 'MS University'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'The cultural capital of Gujarat has elegant bungalows in Alkapuri and Akota and new townships in Bhayli, Gotri and Waghodia Road.',
    styleNote:
      'Baroda’s art-school heritage means clients appreciate craft, colour and curated art walls.',
    priceIndex: 0.97,
    nearby: ['ahmedabad', 'surat', 'anand', 'bharuch'],
    geo: { lat: 22.3072, lng: 73.1812 },
  },
  {
    slug: 'rajkot',
    name: 'Rajkot',
    state: 'gujarat',
    district: 'Rajkot',
    tier: 2,
    localities: [
      'Kalawad Road',
      'University Road',
      'Raiya Road',
      '150 Feet Ring Road',
      'Nana Mava',
      'Amin Marg',
      'Mavdi',
      'Sadhu Vaswani Road',
      'Gondal Road',
      'Race Course',
    ],
    landmarks: ['Watson Museum', 'Race Course Ground'],
    climate: 'hot-dry',
    housing: ['independent', 'gated-villa', 'high-rise'],
    housingNote:
      'Saurashtra’s commercial capital favours independent bungalows and tenements along Kalawad Road and the 150 Feet Ring Road.',
    styleNote:
      'Rajkot’s gold and engineering wealth shows in expansive, generously finished family homes.',
    priceIndex: 0.95,
    nearby: ['ahmedabad', 'jamnagar', 'bhavnagar', 'morbi'],
    geo: { lat: 22.3039, lng: 70.8022 },
  },
  {
    slug: 'bhavnagar',
    name: 'Bhavnagar',
    state: 'gujarat',
    district: 'Bhavnagar',
    tier: 3,
    localities: [
      'Waghawadi Road',
      'Kalanala',
      'Ghogha Circle',
      'Sardar Nagar',
      'Hill Drive',
      'Subhash Nagar',
      'Sidsar',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'A coastal Saurashtra city with a strong independent-home tradition and a growing apartment market on Waghawadi Road.',
    styleNote:
      'Heat and coastal exposure demand a rugged material palette with breathable finishes.',
    priceIndex: 0.9,
    nearby: ['rajkot', 'ahmedabad'],
    geo: { lat: 21.7645, lng: 72.1519 },
  },
  {
    slug: 'jamnagar',
    name: 'Jamnagar',
    state: 'gujarat',
    district: 'Jamnagar',
    tier: 3,
    localities: [
      'Park Colony',
      'Patel Colony',
      'Indira Marg',
      'Summair Club Road',
      'Digvijay Plot',
      'Ranjit Nagar',
      'Khambhalia Road',
    ],
    landmarks: ['Lakhota Lake', 'Reliance Refinery'],
    climate: 'hot-dry',
    housing: ['independent', 'row-house', 'mixed'],
    housingNote:
      'Refinery and brass-part industries support a well-paid professional population in Park Colony and Patel Colony.',
    styleNote:
      'Jamnagar bandhani textiles and brass make authentic local accents.',
    priceIndex: 0.9,
    nearby: ['rajkot'],
    geo: { lat: 22.4707, lng: 70.0577 },
  },
  {
    slug: 'anand',
    name: 'Anand',
    state: 'gujarat',
    district: 'Anand',
    tier: 3,
    aka: ['Vallabh Vidyanagar'],
    localities: [
      'Vallabh Vidyanagar',
      'Karamsad',
      'Amul Dairy Road',
      'Ganesh Chowkdi',
      'Bakrol',
      'Lambhvel Road',
    ],
    landmarks: ['Amul Dairy', 'Sardar Patel University'],
    climate: 'hot-dry',
    housing: ['independent', 'row-house'],
    housingNote:
      'A university and dairy town with many NRI-owned bungalows in Vidyanagar and Karamsad.',
    styleNote: 'Remote-approval workflows are common as owners live abroad.',
    priceIndex: 0.92,
    nearby: ['vadodara', 'ahmedabad'],
    geo: { lat: 22.5645, lng: 72.9289 },
  },
  {
    slug: 'bharuch',
    name: 'Bharuch',
    state: 'gujarat',
    district: 'Bharuch',
    tier: 3,
    aka: ['Ankleshwar'],
    localities: [
      'Zadeshwar',
      'Shravan Chowkdi',
      'Ankleshwar',
      'Dahej Bypass',
      'Bholav',
      'Station Road',
      'GIDC',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'high-rise'],
    housingNote:
      'The Bharuch–Ankleshwar–Dahej petrochemical belt has professional housing demand and new apartments in Zadeshwar.',
    styleNote:
      'Durable, low-maintenance interiors for busy industrial professionals are the typical brief.',
    priceIndex: 0.92,
    nearby: ['vadodara', 'surat'],
    geo: { lat: 21.7051, lng: 72.9959 },
  },
  {
    slug: 'navsari',
    name: 'Navsari',
    state: 'gujarat',
    district: 'Navsari',
    tier: 3,
    aka: ['Valsad', 'Vapi'],
    localities: [
      'Vijalpore',
      'Lunsikui',
      'Eru',
      'Grid',
      'Valsad',
      'Vapi',
      'Tithal Road',
    ],
    climate: 'humid-coastal',
    housing: ['independent', 'mixed'],
    housingNote:
      'South Gujarat’s Navsari–Valsad–Vapi corridor mixes Parsi heritage homes with industrial-town apartments.',
    styleNote:
      'Parsi-influenced interiors — dark teak, tiled floors, lace and brass — are a beautiful local vocabulary.',
    priceIndex: 0.92,
    nearby: ['surat', 'mumbai'],
    geo: { lat: 20.9467, lng: 72.952 },
  },
  {
    slug: 'morbi',
    name: 'Morbi',
    state: 'gujarat',
    district: 'Morbi',
    tier: 3,
    localities: [
      'Ravapar Road',
      'Shanala Road',
      'Sanala',
      'Umiya Circle',
      'Lati Plot',
      'Halvad Road',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'mixed'],
    housingNote:
      'The world’s ceramic-tile capital has a wealthy industrialist population in large independent homes.',
    styleNote:
      'Being at the source lets us use large-format and designer tiles lavishly.',
    priceIndex: 0.9,
    nearby: ['rajkot', 'ahmedabad'],
    geo: { lat: 22.8173, lng: 70.8378 },
  },
  {
    slug: 'bhuj',
    name: 'Bhuj',
    state: 'gujarat',
    district: 'Kutch',
    tier: 3,
    aka: ['Kutch', 'Gandhidham'],
    localities: [
      'Mundra Road',
      'Hospital Road',
      'Sanskar Nagar',
      'Madhapar',
      'Gandhidham',
      'Adipur',
      'Anjar',
    ],
    landmarks: ['Rann of Kutch', 'Aina Mahal', 'Prag Mahal'],
    climate: 'hot-dry',
    housing: ['independent', 'row-house'],
    housingNote:
      'Post-2001 rebuilt Bhuj and the industrial Gandhidham–Mundra belt have well-planned independent homes.',
    styleNote:
      'Kutch mirror-work, Ajrakh block prints and Rogan art are world-class local crafts we design around.',
    priceIndex: 0.92,
    nearby: ['rajkot', 'jamnagar'],
    geo: { lat: 23.242, lng: 69.6669 },
  },

  // ── Rajasthan ──
  {
    slug: 'jaipur',
    name: 'Jaipur',
    state: 'rajasthan',
    district: 'Jaipur',
    tier: 1,
    localities: [
      'C-Scheme',
      'Malviya Nagar',
      'Vaishali Nagar',
      'Mansarovar',
      'Jagatpura',
      'Tonk Road',
      'Bani Park',
      'Civil Lines',
      'Raja Park',
      'Jhotwara',
      'Sirsi Road',
      'Ajmer Road',
      'Vidhyadhar Nagar',
      'Pratap Nagar',
      'Gopalpura Bypass',
      'Sanganer',
    ],
    landmarks: ['Hawa Mahal', 'Amber Fort', 'City Palace'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa', 'heritage'],
    housingNote:
      'The Pink City has spacious villas in C-Scheme and Civil Lines, plotted colonies in Vaishali Nagar and Mansarovar, and new towers on Tonk Road and Jagatpura.',
    styleNote:
      'Jaipur’s craft ecosystem — blue pottery, block prints, marble inlay, jaali screens — gives us the richest local material palette in India.',
    marketNote:
      'Kishangarh marble market is 100 km away; stone sourcing here is unmatched.',
    priceIndex: 0.98,
    nearby: ['ajmer', 'new-delhi', 'jodhpur', 'kota'],
    geo: { lat: 26.9124, lng: 75.7873 },
  },
  {
    slug: 'jodhpur',
    name: 'Jodhpur',
    state: 'rajasthan',
    district: 'Jodhpur',
    tier: 2,
    localities: [
      'Shastri Nagar',
      'Ratanada',
      'Sardarpura',
      'Paota',
      'Chopasni Housing Board',
      'Pal Road',
      'Basni',
      'Kudi Bhagtasni',
      'Air Force Area',
      'Mandore Road',
    ],
    landmarks: ['Mehrangarh Fort', 'Umaid Bhawan Palace', 'Clock Tower'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage', 'gated-villa'],
    housingNote:
      'The Blue City has a strong haveli-restoration and heritage-hotel market alongside modern colonies in Shastri Nagar and Pal Road.',
    styleNote:
      'Jodhpur sandstone, araish lime plaster and carved wood furniture — the city is India’s furniture export hub — define the palette.',
    priceIndex: 0.95,
    nearby: ['jaipur', 'udaipur', 'ajmer'],
    geo: { lat: 26.2389, lng: 73.0243 },
  },
  {
    slug: 'udaipur',
    name: 'Udaipur',
    state: 'rajasthan',
    district: 'Udaipur',
    tier: 2,
    localities: [
      'Hiran Magri',
      'Fatehpura',
      'Bhuwana',
      'Sukher',
      'Panchwati',
      'Shobhagpura',
      'Ambamata',
      'Lake Pichola area',
      'Pratap Nagar',
      'New Bhupalpura',
    ],
    landmarks: ['Lake Pichola', 'City Palace Udaipur', 'Jag Mandir'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage', 'gated-villa'],
    housingNote:
      'The City of Lakes is a luxury-hospitality capital; residential demand centres on Hiran Magri, Bhuwana and lake-facing villas.',
    styleNote:
      'Mewar miniature painting, Rajsamand marble and jharokha detailing bring royal character to homes and boutique hotels.',
    priceIndex: 0.98,
    nearby: ['jodhpur', 'jaipur', 'ahmedabad'],
    geo: { lat: 24.5854, lng: 73.7125 },
  },
  {
    slug: 'kota',
    name: 'Kota',
    state: 'rajasthan',
    district: 'Kota',
    tier: 2,
    localities: [
      'Talwandi',
      'Vigyan Nagar',
      'Mahaveer Nagar',
      'Jawahar Nagar',
      'Dadabari',
      'Rajeev Gandhi Nagar',
      'Indra Vihar',
      'Landmark City',
      'Kunhari',
      'Nayapura',
    ],
    landmarks: ['Seven Wonders Park', 'Chambal Riverfront', 'Kishore Sagar'],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'mixed'],
    housingNote:
      'India’s coaching capital has enormous hostel and PG demand alongside family homes in Talwandi and Vigyan Nagar.',
    styleNote:
      'Kota stone flooring and Kota doria fabric are literally local; durable student-housing interiors are a speciality here.',
    priceIndex: 0.9,
    nearby: ['jaipur', 'bhopal'],
    geo: { lat: 25.2138, lng: 75.8648 },
  },
  {
    slug: 'ajmer',
    name: 'Ajmer',
    state: 'rajasthan',
    district: 'Ajmer',
    tier: 3,
    aka: ['Pushkar'],
    localities: [
      'Vaishali Nagar',
      'Civil Lines',
      'Panchsheel Nagar',
      'Adarsh Nagar',
      'Foy Sagar Road',
      'Pushkar',
      'Kishangarh',
    ],
    landmarks: ['Ajmer Sharif Dargah', 'Ana Sagar Lake', 'Pushkar Lake'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage'],
    housingNote:
      'Ajmer, Pushkar and Kishangarh form a heritage-and-marble triangle with strong hospitality and home demand.',
    styleNote:
      'Being next to Kishangarh’s marble market makes stone-rich interiors exceptionally cost-effective here.',
    priceIndex: 0.9,
    nearby: ['jaipur', 'jodhpur'],
    geo: { lat: 26.4499, lng: 74.6399 },
  },
  {
    slug: 'bikaner',
    name: 'Bikaner',
    state: 'rajasthan',
    district: 'Bikaner',
    tier: 3,
    localities: [
      'Sadul Ganj',
      'Jai Narayan Vyas Colony',
      'Rani Bazar',
      'Gangashahar',
      'Bhinasar',
      'Pawanpuri',
      'Karni Nagar',
    ],
    landmarks: ['Junagarh Fort', 'Karni Mata Temple'],
    climate: 'hot-dry',
    housing: ['independent', 'heritage'],
    housingNote:
      'Desert-city havelis and modern colonies in Sadul Ganj and JNV Colony.',
    styleNote:
      'Usta gold-leaf art and carved sandstone are Bikaner’s signature crafts.',
    priceIndex: 0.9,
    nearby: ['jodhpur', 'jaipur'],
    geo: { lat: 28.0229, lng: 73.3119 },
  },
  {
    slug: 'alwar',
    name: 'Alwar',
    state: 'rajasthan',
    district: 'Alwar',
    tier: 3,
    aka: ['Bhiwadi', 'Neemrana'],
    localities: [
      'Scheme 8',
      'Scheme 10',
      'Bhiwadi',
      'Neemrana',
      'Tijara',
      'Vijay Mandir Road',
      'NEB',
    ],
    climate: 'hot-dry',
    housing: ['independent', 'high-rise', 'gated-villa'],
    housingNote:
      'Bhiwadi and Neemrana’s industrial townships on the NCR fringe drive apartment and villa demand.',
    styleNote:
      'Practical NCR-standard interiors at Rajasthan prices are the sweet spot.',
    priceIndex: 0.95,
    nearby: ['gurugram', 'jaipur', 'new-delhi'],
    geo: { lat: 27.553, lng: 76.6346 },
  },

  // ── Goa ──
  {
    slug: 'panaji',
    name: 'Goa',
    state: 'goa',
    district: 'North Goa',
    tier: 2,
    aka: ['Panaji', 'Margao', 'Vasco', 'Mapusa'],
    localities: [
      'Panaji',
      'Porvorim',
      'Dona Paula',
      'Miramar',
      'Assagao',
      'Siolim',
      'Anjuna',
      'Candolim',
      'Calangute',
      'Mapusa',
      'Margao',
      'Vasco da Gama',
      'Colva',
      'Benaulim',
      'Ponda',
      'Aldona',
      'Saligao',
    ],
    landmarks: ['Basilica of Bom Jesus', 'Fontainhas', 'Dudhsagar Falls'],
    climate: 'tropical-wet',
    housing: ['gated-villa', 'heritage', 'independent', 'high-rise'],
    housingNote:
      'Second homes and villas in Assagao, Siolim and Aldona; apartments in Porvorim, Panaji and Margao; and a thriving boutique-hospitality market on both coasts.',
    styleNote:
      'Indo-Portuguese heritage — azulejo tiles, laterite, oyster-shell windows, deep verandas — inspires a breezy, timeless look.',
    marketNote:
      'Heavy monsoons and salt air demand marine ply, teak, terrazzo and breathable lime finishes.',
    priceIndex: 1.12,
    nearby: ['mumbai', 'pune', 'kolhapur', 'mangaluru'],
    geo: { lat: 15.4909, lng: 73.8278 },
  },
];
