import { SITE_URL } from '@/lib/seo/site';

export const dynamic = 'force-static';

/** Sitemap index pointing at the section sitemaps generated by app/sitemap.ts. */
export function GET() {
  const now = new Date().toISOString();
  const maps = [0, 1, 2, 3].map((id) => `${SITE_URL}/sitemap/${id}.xml`);
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${maps.map((m) => `  <sitemap><loc>${m}</loc><lastmod>${now}</lastmod></sitemap>`).join('\n')}
</sitemapindex>`;
  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
